### ISSUE TITLE
Change Java Version of matsim-example-project

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-libs#1005]
I noticed, that the example poject is still on Java 11. Is this on purpose or should I change it?

**Comment by mrieser** [comment]
Until MATSim 11.x, Java 8 was sufficient. Now with the upcoming release of MATSim 12, the dependencies of the example-project will also require Java 11, so it makes sense to adapt it now.

**Comment by Janekdererste** [comment]
Okay, done.
