### ISSUE TITLE
Do vehicles have a minimum wait time every time they leave/enter a link queue ?

### ISSUE THREAD

**Issue by Nitnelav** [matsim-org/matsim-libs#1016]
Hi there,

Maybe I missed something but, 

it seems vehicles have a minimum wait time every time they leave/enter a link queue...

I made a gist to test my theory, you can replicate it from here : https://gist.github.com/Nitnelav/05037feeb0a5cdbaad79a07366d9c6d3

The vehicle does travel slower on a "split links" trip (10 links of length 10) than on a "basic" (1 link of length 100) one.

You can see the result in the events.xml files bellow : 

With a single "ct" link : 
```
<?xml version="1.0" encoding="utf-8"?>
<events version="1.0">
	<event time="21600.0" type="actend" person="1" link="cl" actType="h"  />
	<event time="21600.0" type="departure" person="1" link="cl" legMode="car"  />
	<event time="21600.0" type="PersonEntersVehicle" person="1" vehicle="1"  />
	<event time="21600.0" type="vehicle enters traffic" person="1" link="cl" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="21601.0" type="left link" vehicle="1" link="cl"  />
	<event time="21601.0" type="entered link" vehicle="1" link="lc"  />
	<event time="21612.0" type="left link" vehicle="1" link="lc"  />
	<event time="21612.0" type="entered link" vehicle="1" link="cr"  />
	<event time="21622.0" type="vehicle leaves traffic" person="1" link="cr" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="21622.0" type="PersonLeavesVehicle" person="1" vehicle="1"  />
	<event time="21622.0" type="arrival" person="1" link="cr" legMode="car"  />
	<event time="21622.0" type="actstart" person="1" link="cr" actType="w"  />
	<event time="28822.0" type="actend" person="1" link="cr" actType="w"  />
	<event time="28822.0" type="departure" person="1" link="cr" legMode="car"  />
	<event time="28822.0" type="PersonEntersVehicle" person="1" vehicle="1"  />
	<event time="28822.0" type="vehicle enters traffic" person="1" link="cr" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="28823.0" type="left link" vehicle="1" link="cr"  />
	<event time="28823.0" type="entered link" vehicle="1" link="rc"  />
	<event time="28834.0" type="left link" vehicle="1" link="rc"  />
	<event time="28834.0" type="entered link" vehicle="1" link="ct"  />
	<event time="28844.0" type="vehicle leaves traffic" person="1" link="ct" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="28844.0" type="PersonLeavesVehicle" person="1" vehicle="1"  />
	<event time="28844.0" type="arrival" person="1" link="ct" legMode="car"  />
	<event time="28844.0" type="actstart" person="1" link="ct" actType="w"  />
	<event time="36044.0" type="actend" person="1" link="ct" actType="w"  />
	<event time="36044.0" type="departure" person="1" link="ct" legMode="car"  />
	<event time="36044.0" type="PersonEntersVehicle" person="1" vehicle="1"  />
	<event time="36044.0" type="vehicle enters traffic" person="1" link="ct" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="36045.0" type="left link" vehicle="1" link="ct"  />
	<event time="36045.0" type="entered link" vehicle="1" link="tc"  />
	<event time="36056.0" type="left link" vehicle="1" link="tc"  />
	<event time="36056.0" type="entered link" vehicle="1" link="cl"  />
	<event time="36066.0" type="vehicle leaves traffic" person="1" link="cl" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="36066.0" type="PersonLeavesVehicle" person="1" vehicle="1"  />
	<event time="36066.0" type="arrival" person="1" link="cl" legMode="car"  />
	<event time="36066.0" type="actstart" person="1" link="cl" actType="h"  />
</events>
```

With the "ct" link split in 10 : 
```
<?xml version="1.0" encoding="utf-8"?>
<events version="1.0">
	<event time="21600.0" type="actend" person="1" link="cl" actType="h"  />
	<event time="21600.0" type="departure" person="1" link="cl" legMode="car"  />
	<event time="21600.0" type="PersonEntersVehicle" person="1" vehicle="1"  />
	<event time="21600.0" type="vehicle enters traffic" person="1" link="cl" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="21601.0" type="left link" vehicle="1" link="cl"  />
	<event time="21601.0" type="entered link" vehicle="1" link="lc"  />
	<event time="21612.0" type="left link" vehicle="1" link="lc"  />
	<event time="21612.0" type="entered link" vehicle="1" link="cr"  />
	<event time="21622.0" type="vehicle leaves traffic" person="1" link="cr" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="21622.0" type="PersonLeavesVehicle" person="1" vehicle="1"  />
	<event time="21622.0" type="arrival" person="1" link="cr" legMode="car"  />
	<event time="21622.0" type="actstart" person="1" link="cr" actType="w"  />
	<event time="28822.0" type="actend" person="1" link="cr" actType="w"  />
	<event time="28822.0" type="departure" person="1" link="cr" legMode="car"  />
	<event time="28822.0" type="PersonEntersVehicle" person="1" vehicle="1"  />
	<event time="28822.0" type="vehicle enters traffic" person="1" link="cr" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="28823.0" type="left link" vehicle="1" link="cr"  />
	<event time="28823.0" type="entered link" vehicle="1" link="rc"  />
	<event time="28834.0" type="left link" vehicle="1" link="rc"  />
	<event time="28834.0" type="entered link" vehicle="1" link="ct_0"  />
	<event time="28836.0" type="left link" vehicle="1" link="ct_0"  />
	<event time="28836.0" type="entered link" vehicle="1" link="ct_1"  />
	<event time="28838.0" type="left link" vehicle="1" link="ct_1"  />
	<event time="28838.0" type="entered link" vehicle="1" link="ct_2"  />
	<event time="28840.0" type="left link" vehicle="1" link="ct_2"  />
	<event time="28840.0" type="entered link" vehicle="1" link="ct_3"  />
	<event time="28842.0" type="left link" vehicle="1" link="ct_3"  />
	<event time="28842.0" type="entered link" vehicle="1" link="ct_4"  />
	<event time="28844.0" type="left link" vehicle="1" link="ct_4"  />
	<event time="28844.0" type="entered link" vehicle="1" link="ct_5"  />
	<event time="28846.0" type="left link" vehicle="1" link="ct_5"  />
	<event time="28846.0" type="entered link" vehicle="1" link="ct_6"  />
	<event time="28848.0" type="left link" vehicle="1" link="ct_6"  />
	<event time="28848.0" type="entered link" vehicle="1" link="ct_7"  />
	<event time="28850.0" type="left link" vehicle="1" link="ct_7"  />
	<event time="28850.0" type="entered link" vehicle="1" link="ct_8"  />
	<event time="28852.0" type="left link" vehicle="1" link="ct_8"  />
	<event time="28852.0" type="entered link" vehicle="1" link="ct_9"  />
	<event time="28853.0" type="vehicle leaves traffic" person="1" link="ct_9" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="28853.0" type="PersonLeavesVehicle" person="1" vehicle="1"  />
	<event time="28853.0" type="arrival" person="1" link="ct_9" legMode="car"  />
	<event time="28853.0" type="actstart" person="1" link="ct_9" actType="w"  />
	<event time="36053.0" type="actend" person="1" link="ct_9" actType="w"  />
	<event time="36053.0" type="departure" person="1" link="ct_9" legMode="car"  />
	<event time="36053.0" type="PersonEntersVehicle" person="1" vehicle="1"  />
	<event time="36053.0" type="vehicle enters traffic" person="1" link="ct_9" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="36054.0" type="left link" vehicle="1" link="ct_9"  />
	<event time="36054.0" type="entered link" vehicle="1" link="tc"  />
	<event time="36065.0" type="left link" vehicle="1" link="tc"  />
	<event time="36065.0" type="entered link" vehicle="1" link="cl"  />
	<event time="36075.0" type="vehicle leaves traffic" person="1" link="cl" vehicle="1" networkMode="car" relativePosition="1.0"  />
	<event time="36075.0" type="PersonLeavesVehicle" person="1" vehicle="1"  />
	<event time="36075.0" type="arrival" person="1" link="cl" legMode="car"  />
	<event time="36075.0" type="actstart" person="1" link="cl" actType="h"  />
</events>
```

**Comment by kainagel** [comment]
Other people know this better than me, and maybe can explain it in more detail.  But in principle, this is correct: When the link travel time is over, a vehicle is moved into a so-called buffer, where it will need another second.  We should probably have a setter that this one second can removed from the "main" link travel time, but that currently ain't there.  Note that the resuld of this also depends a bit on rounding, e.g. if you have a link with travel time 99 sec, and split it into two, I am not sure if it gets split into 2 x (44+1) or 2 x (45 + 1).

If you really need this _exact_, you will have to adjust your free speed of the divided links manually so that the travel time that comes out (=length/freeSpeed) has the one second deducted.

**Comment by Nitnelav** [comment]
Ok, thank you for the explanation. So my roundabouts are going to be a problem :)

![image](https://user-images.githubusercontent.com/5324785/84162043-37f3b900-aa70-11ea-908a-ed5d7fc90393.png)

Could you point me to where I should look approximately in the sources to see if I can manage to implement the setter you mentioned ?

PS : I am trying to keep the exact spatial representation of the links intact from the OSM data. The idea is to calculate distances from links at some point. I am using the JOSM Matsim plugin.

**Comment by Nitnelav** [comment]
Ok so, for future readers (including me), this is what i could gather : 

Matsim calculates stuff based on a timestamp in seconds. Something like : 
```
while (true) {
    doVeryComplicatedStuff(time);
    time++;
}
```
In QSim, "nodes" act as a connection between the "output buffers" of incoming links and the "input buffers" of outgoing links.
The operation of pulling a vehicle from one buffer and putting it into another is done in the `QNodeImpl` class, here  
```
private void moveVehicleFromInlinkToOutlink(final QVehicle veh, Id<Link> currentLinkId, final QLaneI fromLane, Id<Link> nextLinkId, QLaneI nextQueueLane) {
	double now = this.context.getSimTimer().getTimeOfDay() ;
	fromLane.popFirstVehicle();
	this.context.getEventsManager().processEvent(new LinkLeaveEvent(now, veh.getId(), currentLinkId));
	veh.getDriver().notifyMoveOverNode( nextLinkId );
	this.context.getEventsManager().processEvent(new LinkEnterEvent(now, veh.getId(), nextLinkId ));
	nextQueueLane.addFromUpstream(veh);
}
```

It is likely this step just takes one "cycle". In this case, one timstamp increment. So... 1 second.

If this is right, looking at how it's done I can't see any easy way to compensate for this structural delay. 

Post processing the events would work but we would still take the delay into account while scoring the routes...

Will keep looking...

**Comment by sebhoerl** [comment]
Did you try setting the time step to something smaller than one second via code (not via config file)? I think there are only unit tests for time steps larger than one second, but could be worth a try :) At the end, everything is implemented as `double` as far as I know.

**Comment by tthunig** [comment]
If your only issue is keeping the distance of links correct, you can just merge the roundabout links and set the distance as the sum of all previous links. That is also what the NetworkSimplifier does automatically.

Regarding the travel time issue: To be precise, the free speed travel time on a MATSim link excluding the buffer is length/freespeed rounded down to the next time step. As Kai Nagel mentioned, the buffer adds another time step. If you use a time step size of 1 second and your link is 100 m long with a freespeed of 10 m/s, the free flow travel time of your link including the time in the buffer will be 11s. But if you use e.g. 99m and 10 m/s it will be 10s.
This also means that the problem only occurs in constructed scenarios, where length/freespeed is a multiple of the time step size (i.e. integer if you use time step size 1).

I would not recommend using time step size != 1 with the current MATSim version ;-) I recently fixed some bugs according to that but the [pull request](https://github.com/matsim-org/matsim-libs/pull/1004) is not merged yet. I would be very happy if anybody of you that feels somehow responsible for the QSim could have a look and give feedback.

**Comment by kainagel** [comment]
I want to stress what Theresa said: If you need to fix this, change the link geometry.  I had said fixing it via the freeSpeed, but what Theresa writes is even easier: shorten the length.  If you are running from script-in-java, something like

for ( Link link : scenario.getNetwork().getLinks().values() ) {
    link.setLength( link.getLength() - offset ) ;
}

You may have to try around a bit:

* The overall length should not become too short (and in fact there is something in the simulation logic that may make it longer again since otherwise some other things may not work).

* You need to find some equation for offset.  Possibly, it is just "offset = freeSpeed" (since you need the distance travelled in 1sec).

**Comment by Nitnelav** [comment]
Hi, thank you all for your inputs.

I indeed get a `yyyy This will produce weird results because in at least one place (addFromUpstream(...)) everything is pulled to integer values.  Aborting ... (This statement may no longer be correct; I think that the incriminating code was modified.  So please test and remove the warning if it works. kai, sep'14` error when trying timestep <= 1...

Just to be thorough, my goal is to keep the "real" geometry of the link.
I don't think the 1sec delay at nodes is a problem in itself, one could even argue it's more realistic than having no delay at all. It just happen to become an issue when trying to keep the geometry of the links intact because nodes add up quickly on curves :)

Maybe another use of splitting a link into many other small ones would be in order to deduce some kind of speed or acceleration profile by analysing link stats...

But anyway, I will try shortening the length, see if I get any "length too short" error. It does seem to be the easiest fix.

Thank you all again !
