### ISSUE TITLE
Is SwissRailRaptor now the default pt router in v12.0?

### ISSUE THREAD

**Issue by josiekre** [matsim-org/matsim-libs#1018]
I'm having a hard time verifying which pt router is the default now in the latest v12.0 release. Has it been changed to SwissRailRapter?

**Comment by vsp-gleich** [comment]
No, if you don't add SwissRailRaptor to your run class (see below), the old default transit router is used. The only new thing is that SwissRailRaptor is contained in the matsim release and is no longer located in a separate repository.

`controler.addOverridingModule( new AbstractModule() {
				@Override
				public void install() {
					install( new SwissRailRaptorModule() );
				}
			} );`

You can easily check which router is used by searching the log file for **SwissRailRaptor**. You should find e.g. _DATETIME_` INFO SwissRailRaptorData:72 Preparing data for SwissRailRaptor...` if SwissRailRaptor is used. If the default transit router is used check for **TransitRouterNetwork** and you'll find e.g. _DATETIME_` INFO TransitRouterNetwork:402 start creating transit network`.

**Comment by josiekre** [comment]
Thanks @vsp-gleich!

**Comment by josiekre** [comment]
Is there a way for a user to get SwissRailRaptor running using the MATSim GUI? Seems like something that should be configurable in the `config.xml`.

cc: @vsgo222 @gregerhardt

**Comment by mrieser** [comment]
Currently, SwissRailRaptor can only be used by adapting the code as shown above. There is currently no config-switch.
