### ISSUE TITLE
Travis settings for PRs from forks

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/matsim-libs#1036]
I'm putting this issue to continue the discussion from #1035.

The problem was that @Nitnelav was sending a PR from a personal fork (which would be the normal work flow, if you're not explicitly contributor of the MATSim repsository), but it could not be merged, because Travis currently only builds branches _inside_ of the MATSim repository.

Now:
- @mrieser changed the Travis settings to also build _pull requests_, not only _branches_
- Still, it would be necessary to change the merge restrictions in the repository to require "Travis PR", not "Travis Branch", as it is currently
- @michalmac had the argument that now everything is built frequently (twice per PR at least)

One option could be to disable building all branches (except `master`), and build only PRs otherwise. I'm not sure if people actively use the branch builds currently to do the testing (I'm trying to make all tests run before I push anything).

**Comment by kainagel** [comment]
For me, having the build server build the branches was one of the strong positive points of travis over jenkins.  I normally (but not always) run "matsim" locally, but I indeed leave running the contribs nearly always to travis.

**Comment by jfbischoff** [comment]
I also rely on travis for running branches quite heavily. Using Windows, running all tests sometimes causes IOExceptions that make tests fail, so using travis instead is quite comfortable.
