### ISSUE TITLE
IdMap very slow for larger scenarios

### ISSUE THREAD

**Issue by d-roeder** [matsim-org/matsim-libs#1044]
Hi ,

we realized that IdMap becomes very slow for larger scenarios, i.e millions of agents, when filling it. I fixed that issue temporally (and unfortunatelly forgot to report) with commit fafc3ff6d0a3d9b84e4ccba441684a4f2430f087. I think my solution is not a reasonable fix for everyone as it would be a waste of memory for smaller scenarios. 

My suggestion would be something like 

```java
public class IdMap<T, V> implements Map<Id<T>, V>, Iterable<V> {

	private static final String KEY = "idMapSize";
	private static final int DEFAULT_SIZE = 100;
	
	private Class<T> idClass;
	private final int sizeIncrement;
	private int size = 0;
	private Object[] data;


	public IdMap(Class<T> idClass) {
		this(idClass, Math.max(Id.getNumberOfIds(idClass), System.getProperties().getOrDefault(KEY, DEFAULT_SIZE)));
	}
	...
}
```
Now the advanced user would be able to configure the initial size without any drawbacks for the standard-user via commandline with 

```shell 
java -DidMapSize=999999 ....
```

Does anyone see a problem here?

Best,
Daniel

**Comment by michalmac** [comment]
Maybe the underlying array expansion should be relative, e.g. x1.5 or x2.0? So that we have some kind of self-adaptation mechanism?

**Comment by d-roeder** [comment]
hm, this would solve the performance-issue. But wouldn't it lead to a memory issue for large scenarios?

**Comment by michalmac** [comment]
- With the 1.5 factor we do not risk so much.
- It's an array of `Objects`, so in the worst case 8 bytes per empty cell (e.g. 8 MB for 1 million empty cells).

**Comment by d-roeder** [comment]
ah, right. I forgot that it is only the memory for the pointer and not for the object ... thanks
