### ISSUE TITLE
org.matsim.analysis.TripsAndLegsCSVWriter imports org.apache.commons.lang3.ArrayUtils, but maven does not (matsim 12.0)

### ISSUE THREAD

**Issue by idshklein** [matsim-org/matsim-libs#1072]
https://github.com/matsim-org/matsim-libs/blob/12.x/matsim/src/main/java/org/matsim/analysis/TripsAndLegsCSVWriter.java#L33

**Comment by vsp-gleich** [comment]
org.apache.commons.lang3.ArrayUtils is a dependency of org.apache.commons:commons-csv, which is included in the respective pom: [https://github.com/matsim-org/matsim-libs/blob/c5fbac859d3357be951a68a9dc9826c435574db5/matsim/pom.xml#L402-L406](https://github.com/matsim-org/matsim-libs/blob/c5fbac859d3357be951a68a9dc9826c435574db5/matsim/pom.xml#L402-L406)

(see [https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.8/commons-csv-1.8.pom](https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.8/commons-csv-1.8.pom))

It should be loaded automatically and it is loaded by the build server and my IntelliJ.
