### ISSUE TITLE
At least the FREEFLOW condition must be specifed for all emission factor keys

### ISSUE THREAD

**Issue by ahmad-fz89** [matsim-org/matsim-libs#1082]
I am using MATsim 12.0 and working on emission(HBEFA 3). I added the required link attributes to the network, engineInformation to the vehicles, and HBEFA .text files to the config. Simulation is run correctly when there is only one vehicle. however, adding multiple vehicles to the simulation and interactions with other agents prevent calculation of the traffic stage (that must be either free-flow or stop and go) and consequently running the WarmEmissionAnalysisModule. The error is: 
ERROR SimStepParallelEventsManagerImpl$ExceptionHandler:420 Thread class org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable0 died with exception while handling events.
java.lang.RuntimeException: At least the FREEFLOW condition must be specifed for all emission factor keys. It was not found for PASSENGER_CAR; null; URB/LOCAL/50; null; petrol (4S); >=2L; PC-P-Euro-1

The log error file is attached.
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-libs/files/4949825/logfileWarningsErrors.log)

Could someone please help me to handle this error?

Thanks

**Comment by jfbischoff** [comment]
Would you mind posting this issue here?
https://github.com/matsim-org/matsim-code-examples/issues

**Comment by ahmad-fz89** [comment]
Thanks for your reply. I will post my next problems over there.
I found the problem. It was supposed to be "Local", not "LOCAL". bit silly mistake in coding.
