### ISSUE TITLE
New default ParallelEventsManager breaks single threaded use-cases

### ISSUE THREAD

**Issue by rakow** [matsim-org/matsim-libs#1091]
The default EventManager returned by ` EventsUtils.createEventsManager();` was changed to be a `ParallelEventsManager`.

Unfortunately this creates problems if it is used in single threaded use-cases outside the MATSim event loops, such as
reading in all events from a file.

It seems the queue will overflow, because no events are being processed. Potentially also if events are processed to slowly, as there seems no mechanism to handle back pressure if the consumers are too slow.

Also see attached stacktrace:
```
java.lang.IllegalStateException: Queue full
	at java.base/java.util.AbstractQueue.add(AbstractQueue.java:98)
	at java.base/java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:326)
	at org.matsim.core.events.ParallelEventsManager.processEvent(ParallelEventsManager.java:150)
```
As a workaround for now the single threaded event manager has to be instantiated manually.

**Comment by mrieser** [comment]
Can you provide a code snippet how you set up the events processing? 
Looking at some test code, I often see the following pattern:

```java
EventsManager events = EventsUtils.createEventsManager();
EventsCollector collector = new EventsCollector();
events.addHandler(collector);
events.initProcessing();
new MatsimEventsReader(events).readFile(filename);
events.finishProcessing();
```

So it seems necessary to call `initProcessing` and `finishProcessing`, and the handlers must be added before `initProcessing` is called...
If you can get it running with this, we should probably think how we could guide users to this, e.g. throw Exceptions when handlers are added after `initProcessing`, or when events are to be handled before `initProcessing` was called.

**Comment by rakow** [comment]
The call to  `.initProcessing()` was indeed missing. It does work fine if it is done as in your example.

So some kind of exception would be nice, as these calls can be easily missed and there was never any problem or warning not doing these before.

**Comment by tschlenther** [comment]
I also faced problems when using MatsimEventsReader, at several places.
The mentioned fix works fine though.
I incorporated in matsim-code-examples on the 12.x branch in all places i could find and will do that for matsim-berlin, too.

**Comment by rakow** [comment]
Probably it is not even a bug in the current parallel events manager. They just add multiple handlers that somehow depends on each other and won't work when each of them is running in a separate thread.

**Comment by kt86** [comment]
A student in the advanced class) has a problem, that he gets at some point the "queue full" exception. He his running the emissions analysis for a berlin 1pct scenario.

The fix mentioned above with 
> So it seems necessary to call initProcessing and finishProcessing, and the handlers must be added before initProcessing is called...
does not helped. 

I played around a bit and reduced the number of emission events that were thrown (by setting a lot of links to length = 0 * --> no emissions were calculated for them). After that, the script runs through without error. 
So it seems to be an issue with the number of events that needs to be processed.

* is is not a very nice way to avoid the calculation, but it worked. Maybe we find there a better solution, e.g. `non_hbefa_link` -- based on the idea of the `non_hbefa_vehicle`

**Comment by kt86** [comment]
During trying out other options of the ParallelEventsManager, I found a public constructor where the queue size can be set:
`ParallelEventsManager(final boolean syncOnTimeSteps, int eventsQueueSize)`

Maybe we have to go away from the default implementation (via `EventsUtils.createEventsManager()`) and "play around" a bit with the explicit definition of the `ParallelEventsManager(final boolean syncOnTimeSteps, int eventsQueueSize)` to find a feasible queue size for the offline emission calculations.  
The problem with the chronological order (#1347) in the offline emission analysis must also be investigated futher.

**Comment by mrieser** [comment]
> A student in the advanced class) has a problem, that he gets at some point the "queue full" exception.

What version of MATSim was used? In the original version of the code, as shown in the Stacktrace at the very top of this issue, `this.eventqueue.add(...)` was used, which could result in the exception. I changed this to `this.eventqueue.put(...)` which should not generate the exception in early December.  In my tries back then, I was not able to reproduce the exception, even with very low values for `eventsQueueSize`.

**Comment by kainagel** [comment]
please Please PLEASE throw an exception.  :-)

On 30. Jul 2020, at 10:20, rakow <notifications@github.com<mailto:notifications@github.com>> wrote:



The call to .initProcessing() was indeed missing. It does work fine if it is done as in your example.

So some kind of exception would be nice, as these calls can be easily missed and there was never any problem or warning not doing these before.
