### ISSUE TITLE
Is Bikesharing via Carsharing Extension viable?

### ISSUE THREAD

**Issue by RealInfinity** [matsim-org/matsim-libs#1113]
Hello,

is it possible to easily adapt the Carsharing Extension to Bikesharing? 

By "easy" I would understand small changes like exchanging the vehicle type on the screen below ("car"->"bike") or similiar adaptions.

![image](https://user-images.githubusercontent.com/63114439/90902137-4f361780-e3cc-11ea-862f-dd499a643c45.png)

Many thanks in advance!

**Comment by joaohenriqueluz** [comment]
Hey there 👋🏻 I'm in a similar situation, and I was wondering if you ever found out how to solve this issue. Were you able to get a bike sharing extension?
Best regards!

**Comment by RealInfinity** [comment]
Hey, I didn't continue with that... but I'm pretty sure that it isn't that easy :/

**Comment by joaohenriqueluz** [comment]
Thank you for the quick response! No problem, I'll see what I can do... 
Best of luck!

**Comment by sebhoerl** [comment]
We (@balacmi + me) have recently developed a new contrib which is currently living here:

https://github.com/eqasim-org/matsim-sharing

... and which should be ported to the main repository soon. It is basically a wrapper around any transport mode in MATSim and it makes it a shared service, either station-based or freefloating. So it makes it easy to set up a bike-sharing system either with network-simulated/routed or teleported bikes. Have a look if you think it might be interesting.

There is a preprint about the extension here:
https://www.researchgate.net/publication/351069421_Simulation_of_intermodal_shared_mobility_in_the_San_Francisco_Bay_using_MATSim

**Comment by balacmi** [comment]
I was in the middle of writing when @sebhoerl answered. He explained nicely the main points. 
Currently the sharing contrib is based on MATSim 12.0, but I should find some time to make an update to MATSim 13.0 soon.

**Comment by joaohenriqueluz** [comment]
Hello, thank you! I will definitely give it a look!

**Comment by tschlenther** [comment]
> 
> 
> We (@balacmi + me) have recently developed a new contrib which is currently living here:
> 
> https://github.com/eqasim-org/matsim-sharing
> 
> ... and which should be ported to the main repository soon. It is basically a wrapper around any transport mode in MATSim and it makes it a shared service, either station-based or freefloating. So it makes it easy to set up a bike-sharing system either with network-simulated/routed or teleported bikes. Have a look if you think it might be interesting.
> 
> There is a preprint about the extension here:
> https://www.researchgate.net/publication/351069421_Simulation_of_intermodal_shared_mobility_in_the_San_Francisco_Bay_using_MATSim

thank you really much for sharing this. We also had a look into that and it looks quite interesting. We'll try using it for our matsim-hamburg scenario...
