### ISSUE TITLE
RFC: PersonScoreEvent

### ISSUE THREAD

**Issue by mrieser** [matsim-org/matsim-libs#1115]
I currently need to write a special scoring function that needs to take various events into account, which I am currently not able to do  with a scoring function. (For more details, see the "Use case" section below). So I thought the easiest way to solve this was to implement a custom EventsHandler, that calculates all the data it needs and also calculates the score-term it is responsible for, and then creates a `PersonScoreEvent` similar to the `PersonMoneyEvent`, which can be collected by a ScoringFunction and added to an agents score.

### I propose the following changes to MATSim:

- A new Event type: `PersonScoreEvent`
- The new event would have the following attributes:
  - `Id<Person> personId`
  - `double amount`
  - `String kind`
- A new interface `PersonScoreEventHandler`
- Adapted Event-readers (XML, JSON)
- Adapt the default scoring function factory to also listen to `PersonScoreEvent`s.

### Potential benefits:

- custom scoring functions would become simpler to implement, as they would just boil down to an additional events handler, which many users might already be more familiar.
- Using events to communicate the (partial) scores is a step towards the more modern "event-based communication" to let different parts of complex systems interact.
- One could even think about retrofitting the existing Leg- and ActivityScoringFunctions into just emitting PersonScoreEvents, in the end simplifying the actual ScoringFunction into just collecting the amounts from PersonScoreEvents.
- By retrofitting the existing scoring calculations into just emitting PersonScoreEvents with a specific `kind` would allow interested users to easily collect the score parts (In the past, there have been repeated requests to get information about the parts that make the score, e.g. what amount comes from activities, what amount from traveling, and what amount from e.g. monetary costs). Now all this information would be available in the events, so users could easily collect this if they need it.

### I have the following questions:

- General: Any opposition into adding such a `PersonScoreEvent`?
- Is `kind` a good name for the informative attribute, or should a better name be used? `type` cannot be used, as it would conflict with the event-type. `purpose` as in the `PersonMoneyEvent` doesn't fit well in my opinion for score, but I might be wrong. Any alternative names proposed?
- Would you support the idea of refactoring the current custom-scoring functions into pure event handlers, or would it possibly break too many use cases where custom scoring functions were already used in the past?

### Use case:

We want to give pt passengers different scores, depending on whether they are in a full/overcrowded transit vehicle, or in one with rather low-occupancy. It should represent a kind of "service quality". With Leg- or TripScoring, I'm able to figure out if an agent was on a pt-trip, but not how the occupancy of this pt vehicle is. For this, I need a separate event handler that collects the required information. But, as the scoring function basically also runs as a separate EventsHandler, the scoring and my data-collection event handler likely run in different threads when using multithreaded events handling. This can lead to race conditions, where the data-collecting thread may not yet have processes all the required data for the scoring, leading to missing data or even NullPointerException, depending on the implementation details. The current scoring functions only receive `PersonEvent`s for the specific person, but in my case I would also need the events of other persons entering the same vehicle, and also the vehicle events itself to know when a vehicle arrives or departs a stop. So, with the current design I'm not really able to implement the planned functionality.

**Comment by sebhoerl** [comment]
Without having an overview about potential implications for past custom scoring functions, I like the approach. I am currently contemplating how to further integrate the discrete choice components and scoring (ideally I would like to use the same utility functions that are usually more complex than the standard scoring functions). I have the feeling that this could simplify this a lot.

Regarding output, wasn't there lately also developments towards only selectively writing out certain event types? This could avoid inflating the events files in case the scores are not needed in post-processing.

**Comment by kainagel** [comment]
I think we at VSP had the same idea some time ago, even implemented a prototype, but did not get around finishing it.  Having a "score" event that works similar to a "money" event, but in score space would solve many of our scoring function problems since one could just add these terms instead of having to replace the whole scoring function.

**Comment by tschlenther** [comment]
> 
> I think we at VSP had the same idea some time ago, even implemented a prototype, but did not get around finishing it. Having a "score" event that works similar to a "money" event, but in score space would solve many of our scoring function problems since one could just add these terms instead of having to replace the whole scoring function.

True. That was on the long-time TODO list. After all, i would also appreciate and support this idea.

>     * Is `kind` a good name for the informative attribute, or should a better name be used? `type` cannot be used, as it would conflict with the event-type. `purpose` as in the `PersonMoneyEvent` doesn't fit well in my opinion for score, but I might be wrong. Any alternative names proposed?

`cause` popped up in my mind when reading this. `kind` leaves out more space for interpretation, though.

**Comment by mrieser** [comment]
Thanks for your comments. I've gone along and implemented a first version of the new Event which I'm now testing. If it works as expected, it will get merged sometime along with my other work on SwissRailRaptor.

**Comment by mrieser** [comment]
A PersonScoreEvent was implemented in b48bfe9 and merged as part of #1198.
