### ISSUE TITLE
Emission calculation crashes (when using drt)

### ISSUE THREAD

**Issue by markusstraub** [matsim-org/matsim-libs#1127]
We try to combine drt with offline emission calculation (with MATSim 12.0) but noticed that the emission calculation crashes quite often with the following error:

    Average speed has been calculated to 0.0 or a negative value. Aborting...

I traced this to the following line in `WarmEmissionHandler.handleEvent(LinkLeaveEvent)`:
https://github.com/matsim-org/matsim-libs/blob/94dd3bca2e13e14acc5960efee7ec952aa31ecff/contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionHandler.java#L185

The relevant snippet from the `events.xml`, which I am processing after the simulation, is here:

```xml
<event time="24673.0" type="entered link" link="63894" vehicle="_saev95"  />
<event time="24681.0" type="left link" link="63894" vehicle="_saev95"  />
<event time="24681.0" type="entered link" link="98615" vehicle="_saev95"  />
<event time="24689.0" type="vehicle leaves traffic" person="_saev95" link="98615" vehicle="_saev95" networkMode="car" relativePosition="1.0"  />
<event time="24689.0" type="PersonLeavesVehicle" person="_saev95" vehicle="_saev95"  />
<event time="24689.0" type="arrival" person="_saev95" link="98615" legMode="car"  />
<event time="24689.0" type="actstart" person="_saev95" link="98615" actType="DrtBusStop"  />
<event time="24689.0" type="PersonLeavesVehicle" person="107_7576_1_1" vehicle="_saev95"  />
<event time="24749.0" type="actend" person="_saev95" link="98615" actType="DrtBusStop"  />
<event time="24749.0" type="actstart" person="_saev95" link="98615" actType="DrtStay"  />
<event time="24749.0" type="actend" person="_saev95" link="98615" actType="DrtStay"  />
<event time="24749.0" type="departure" person="_saev95" link="98615" legMode="car"  />
<event time="24749.0" type="PersonEntersVehicle" person="_saev95" vehicle="_saev95"  />
<event time="24750.0" type="vehicle enters traffic" person="_saev95" link="98615" vehicle="_saev95" networkMode="car" relativePosition="1.0"  />
<event time="24751.0" type="left link" link="98615" vehicle="_saev95"  />
<event time="24751.0" type="entered link" link="98616" vehicle="_saev95"  />
<event time="24758.0" type="PassengersRequest scheduled" person="52_6443_4_2" mode="drt" request="drt_143" vehicle="_saev95" pickupTime="24862.987393857657" dropoffTime="25168.77216212862"  />
<event time="24760.0" type="left link" link="98616" vehicle="_saev95"  />
<event time="24760.0" type="entered link" link="98615" vehicle="_saev95"  />
<event time="24799.0" type="left link" link="98615" vehicle="_saev95"  />
```

The crash happens for the last event at `24799.0` because the line of code resolves to:

```
travelTime = leaveTime - enterTime - departureTime + arrivalTime; 
travelTime = 24799.0 - 24760.0 - 24750.0 + 24689.0
travelTime = -22
```

Here the arrival time of the **previous trip** is incorrectly used in the calculation, leading to a negative travel time.

Two possible fixes come to my mind:
1. Why are the departure and arrival time used for calculating the travel time in the first place? Is the link enter and leave time not enough for calculating the driving speed? Simply remove the departureTime and arrivalTime from the calculation.
2. Avoid mixing departure and arrival times belonging to different trips, e.g. by removing entries for a vehicle in `this.vehicleLeavesTraffic` and `this.vehicleEntersTraffic` after traffic was left.

I also wonder why this problem is not triggered for agents that do not use drt but simply a car to get to work and go home from work again.

Thoughts or hints by the original author or maintainer would be appreciated.

**Comment by kt86** [comment]
Hello Markus,

> I also wonder why this problem is not triggered for agents that do not use drt but simply a car to get to work and go home from work again

It looks like the drt vehicle drives on the departing link (9861**5**) twice between the departure @ 24750.0 and any the arrival anywhere else later. I don't have a case in mind, where "normal" agents (without withinday-replanning) would do that. But here the drt vehicle has a "PassengerRequest scheduled" while driving on the next link (9861**6**). As result it seems to "turn around" and drive again on link 9861**5**.

As far as I see on the first quick view, this problem here only occurs, if the vehicle drives a second time on the departure link. In other cases the calculation should only be https://github.com/matsim-org/matsim-libs/blob/94dd3bca2e13e14acc5960efee7ec952aa31ecff/contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionHandler.java#L175-L181 

--> 
your proposal No 1 is done for `almost` all cases  - except this one here :(
No2 sounds reasonable to me. (Unfortunately I don't have the time to fix it today)  

Best,
Kai MT

**Comment by markusstraub** [comment]
Hi Kai,

thank you for the quick reply and the observation that the vehicle enters the link twice. I had a more detailed look at the code and I think i understood it better now - and that the mix of arrival time and departure time of two adjacent trips is intentional:

The else branch in question handles links where the person arrives with a car, spends some time, and then leaves again. We need to remove the stay time in order to get the pure travel time. 

If that is correct here is my proposed fix:

```java
} else {
	double arrivalTime = this.vehicleLeavesTraffic.get(vehicleId).getSecond();
	double departureTime = this.vehicleEntersTraffic.get(vehicleId).getSecond();
	travelTime = leaveTime - enterTime - departureTime + arrivalTime;
	
	// suggested bugfix starts here:
	// now that we substracted the time spent on the link outside of the vehicle
	// we delete these events (so that when the link gets crossed once more
	// the departure/arrival time are not wrongly taken into account) 
	this.vehicleLeavesTraffic.remove(vehicleId);
	this.vehicleEntersTraffic.remove(vehicleId);
}
```

Best regards, Markus

**Comment by kt86** [comment]
Hi Markus,

sounds good for me. Thanks for the code!
I have put it into the code: `fixEmissionsCalculation1127` branch.
All (existing) emissions & drt tests are still green locally. That's good. :)

Can you just try to run your example using that branch and report back?
(Or even better write a small test, e.g. using an Event file only containing that trip of vehicle`_saev95`. If you provide me the relevant files for that, I can also do it next week. 
I think it would be good to have a test for it, so it will not be removed (accidentally) in the future without notice)

Best regards,
Kai

**Comment by markusstraub** [comment]
Hello Kai!

I successfully ran my example with a locally modified version of MATSim 12.0, so if your tests also pass then this seems to be a valid fix.
I agree a unit test would be great but I don't see a quick way of writing one and unfortunately I can not invest more time in this bugfix. I am attaching all events for my test vehicle *_saev95*, but I fear that you can not use it for unit tests out of the box since the referenced links are from a graph we generated ourselves. Maybe you can use [a minimal part of these events](https://github.com/matsim-org/matsim-libs/files/5142856/output_events__only_saev95.xml.gz) and fix the link ids so that they match a test graph available for MATSim's unit tests?

Best regards, Markus
