### ISSUE TITLE
Emissions module

### ISSUE THREAD

**Issue by MahmoudYounes** [matsim-org/matsim-libs#1207]
Hi all,

I am trying to implement a research paper that makes use of the emission module. I want to calculate the car warm and cold emissions across the simulation. I could not find an example that uses the emission module nor a documentation that describes how to register it to be used in the QSim simulation loop. 

I would appreciate any guidance or help on that. 

Thanks a lot in advance!

disclaimer: I am sorry if I am using the wrong channel to ask this question I searched for proper channels but could not find one.

**Comment by JWJoubert** [comment]
I suggest you have a look at the MATSim book. There are also a number of `Run*` classes in [`org.matsim..contrib.emissions.example](https://github.com/matsim-org/matsim-libs/tree/master/contribs/emissions/src/main/java/org/matsim/contrib/emissions/example) package.
