### ISSUE TITLE
Failing test_VehicleTypeToVehiclesAssignmentIsReadCorrectly

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/matsim-libs#1242]
When I run "all tests" in Eclise for the `matsim` main package, I have one failing unit test at `VehicleReaderV2Test.test_VehicleTypeToVehiclesAssignmentIsReadCorrectly`. It is the very first Assert, checking for null. When I run the test independently, it passes, which makes it hard to figure out what is happening.

Did anybody else encounter such behaviour? I thought it might be the JDK, so I tried with Adopt OpenJDK 11 LTS and 15 Latest, and also with standard java.net OpenJDK 11. Everywhere the same. Any ideas?

**Comment by michalmac** [comment]
I guess same issue as here: #771 -> #769

**Comment by sebhoerl** [comment]
Ok, so I think the problem is the "global state" of the unit test, because the `Id.create` are called to initialize the class variables, and when many tests are run, somewhere in between somewhere `Id.resetCache` is called, which messes up the lookup later on (because ID 23 is looked up, which now has a different index). I'll try to move setting the reference IDs in the `setUp` method.

**Comment by michalmac** [comment]
Resetting the cache is also an option (it's used in a few unit tests already). But I am not sure if this is always the right solution: should iteration order (whatever it is) impact reading vehicles?

**Comment by sebhoerl** [comment]
I think the point is the `resetCache` can (and should) only be called from the unit tests. So in any other case (iteration order) things will not be different, because IDs are created only once in the VM and thread-safe. The problem is just that `resetCaches` is called at some points in the unit tests, which makes a call to `Id.create("xyz")` ambiguous if it is in the class variables, it seems.

**Comment by michalmac** [comment]
Right. This issue with the reader test is something different than what we had with the writer test. Here we have the mismatch between index and id.

Some of my thoughts around `Id.index`:
- the order of tests is platform dependent (for exactly the same set of test), so even without calling `resetCaches` at some places we may have different index-id mappings.
- I am sure we could write some sort of a plugin/listener/executor for jUnit that will automatically reset the cache before each individual test. Doing it manually is not so great.
- in places where we switched from `LinkedHashMap` to `IdMap` we have not only different ordering but also potentially non-deterministic ordering (e.g. if IDs were previously created in parallel)
- Two equal `Id`s according to our definition (e.g. vehicleId and personId with the same when "string id") may have different indices, which may lead to bugs. Probably we should switch to a stricter equality definition.

**Comment by michalmac** [comment]
> Two equal Ids according to our definition (e.g. vehicleId and personId with the same when "string id") may have different indices, which may lead to bugs. Probably we should switch to a stricter equality definition.

In other words: `IdMap<X,Y>` is not fully compatible with `Map<Id<X>,Y>`.
