### ISSUE TITLE
Travis has suspended builds

### ISSUE THREAD

**Issue by vsp-gleich** [matsim-org/matsim-libs#1259]
I just tried to help @luchengqi7 to get his pull request #1253 [tested and merged which is stuck on travis since Friday](https://travis-ci.com/github/matsim-org/matsim-libs/builds/203073892). Travis is showing me a message: 
_Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting._

I first thought this is somehow restricted to my account, but it does not work for @luchengqi7 either.

Any ideas on how to proceed?

**Comment by kt86** [comment]
Looks like, that there is (now?) a limit in computation time per month, that is free for open source projects: https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source .
The credits mentioned there are computed per started build minute:  https://docs.travis-ci.com/user/billing-overview/#usage---credits
The free plan seems to offers 10k credits, which is in fact a maximum of 1000 build minutes (depending on the OS of the build: 10-50 credits/min).

**Comment by kt86** [comment]
... and we have used 11.570 credits for this month: https://travis-ci.com/organizations/matsim-org/plan

**Comment by michalmac** [comment]
Maybe try to uncheck this option:
![image](https://user-images.githubusercontent.com/9891415/100124762-5b72ba80-2e7c-11eb-84ea-5cc6e750537d.png)

**Comment by mrieser** [comment]
Thanks for the hint, @michalmac ! I remember that Travis forced users to switch from Travis.org to Travis.com recently, also for OSS projects. Most likely, this "credit limit" was introduced when we switched.
I now tried to switch off this setting, let's see what happens.

**Comment by mrieser** [comment]
The Travis documentation states:
> Credits vs. OSS Only Credits #
> 
> Credits can be used to build both over private and public repositories.
> 
> On occassion, an allotment of OSS Only credits may be granted by Travis CI. These credits may be used only for builds over public repositories and are meant for open source support. The OSS credits may be assigned as one time pool or renewable pool, subject to case by case assesment of Travis CI staff.
> 
> The OSS credits is a pool of credits completely separate from regular credits, with separate credits balance tracking.

MATSim currently has 0 OSS credits, so it might actually not help :-(

**Comment by mrieser** [comment]
It's maybe time to switch to GitHub Actions instead of Travis. Or to GitLab, where we could provide additional own runners as well.

**Comment by mrieser** [comment]
Of relevance: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by kainagel** [comment]
The blog states that we could apply for OOS hours.  Shouldn't we do that?  They say that they had abuse by bitcoin miners etc.; evidently, this is not what we are.  

Re gitlab: We have our own build servers integrated with tu-berlin gitlab.  Same hardware as we use for jenkins.  Would not be a big problem to procure more hardware if necessary.   I am, however, a bit wary of moving since that always consumes time.  But if you say that this is the better way to go we will do it.  Also if you think that we should switch to github actions (although I think that we will be facing the same issue there eventually).

**Comment by jfbischoff** [comment]
Couldn't we upgrade the current jenkins server at TUB and continue using it in combination with github? 

Our internal builds run very smoothly on jenkins, however unfortunately there is no reasonable way to connect them with github.

**Comment by michalmac** [comment]
Just a quick update: I started playing with GH Actions. Looks very promising:
- I like the structure of the config
- 20 parallel jobs!
- conditional executions (will dive into this so we could speed up build if git-diff is limited to contribs only).
You can already see some experiments: https://github.com/matsim-org/matsim-libs/actions

**Comment by JWJoubert** [comment]
> Re gitlab: We have our own build servers integrated with tu-berlin gitlab. Same hardware as we use for jenkins. Would not be a big problem to procure more hardware if necessary. I am, however, a bit wary of moving since that always consumes time. 

For what it is worth, we are currently procuring a replacement server on our side. Adding a VM dedicated to GitLab-CI (which we already have set up on our GitLab repositories) is an option.
