### ISSUE TITLE
code coverage (cobertura) did not survive switch away from java8

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-libs#1270]
http://ci.matsim.org:8080/view/CodeCoverage/ is failing, and has been failing for approx. 3/4 year now.  :-(

Reason seems to be that cobertura needs tools.jar, but tools.jar no longer exists.  

https://github.com/cobertura/cobertura/issues/271

Switch to JaCoCo?  Other suggestions?  And who would volunteer to do the work?  And where would one change it on jenkins?  (I guess that one needs to change the corresponding mvn command on jenkins.)

(I tend to think that it is good to have this, even if we only look at this only during the matsim classes.  In principle, could run it locally, but since it takes quite some time, it is nice to have it prefabricated.)

**Comment by michalmac** [comment]
I think there are ways to integrate it with GH Actions (if we want to). Just 2 first things that I found:
- https://github.com/marketplace/actions/jacoco-badge-generator
- https://github.com/codecov/codecov-action

I may have a look at it (somewhere at the end of December?)

**Comment by michalmac** [comment]
and this one: https://github.com/marketplace/actions/reportgenerator

**Comment by mrieser** [comment]
I have no enabled JaCoCo to run on Jenkins: http://ci.matsim.org:8080/view/CodeCoverage/

We lost the coverage-history when switching tools, and the coverage-table is not that colorful anymore, but the data is there again.

**Comment by kainagel** [comment]
Ah, super.

However: As far as I can see, this only shows code coverage for the whole project, or is there a way to look into individual packages/classes how it was possible before?

**Comment by mrieser** [comment]
you need to go to a specific build, e.g. http://ci.matsim.org:8080/view/CodeCoverage/job/MATSim_M2_CodeCoverage/578/, then you can click on "Coverage Report" in the sidebar, leading you to http://ci.matsim.org:8080/view/CodeCoverage/job/MATSim_M2_CodeCoverage/578/jacoco, which gives you the view of the separate packages, where you can further drill down.

**Comment by kainagel** [comment]
Oh great thanks a lot.
