### ISSUE TITLE
Core has two Controler Classes - Very Confusing

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-libs#1273]
The matsim core has two controler classes. The 'real' one under ```org.matsim.core.controler.Controler``` and some other under ```org.matsim.run.Controler```. 

I find this very confusing especially because the 'run' package name suggests it could also include the Matsim-Controler Class to start a matsim run. 

This class was created by @mrieser . Maybe you can give some insight whether this could be re-named or removed?

**Comment by kainagel** [comment]
The original idea was that run.Controler would be the outward facing API, and core.Controler inward facing.

But it also causes problems in teaching, and I would vote for removing it.

Maybe set it to deprecated first wait 12 months ...

**Comment by Janekdererste** [comment]
Haha, the usual way. I'll make the change.

**Comment by jfbischoff** [comment]
Whilst we're on it, maybe it is also a good opportunity to add a second l to the other controller?

**Comment by Janekdererste** [comment]
I've removed the 'automerge' label from the pr. So, there is time to discuss now.

Though it is funny, that such a central component has a typo and I appreceate the effort of pulling through with it for over a decade, I'd vote for changing it. That said, I don't have a strong oppinion on this matter

**Comment by michalmac** [comment]
Some of us even started typing control(l)er-related variables or other classes with `ll`.

Let's maybe add yes/no votes under @jfbischoff comment?

**Comment by kainagel** [comment]
I would be ok with changing the name if we can define a transition path.

On the Java side, this is relatively easy: Rename class, keep old class delegating everything to the new class, set old class to deprecated, wait, eventually (maybe in the far future) remove. 

Same with `config.controller()...` then delegating to ...

More difficult: How to deal with the `controler` module in the xml config.  Suggestions? Maybe we could no longer accept the old spelling and write a meaningful error message.

**Comment by jfbischoff** [comment]
>More difficult: How to deal with the controler module in the xml config. Suggestions? Maybe we could no longer accept the old spelling and write a meaningful error message.

That would be a very clean solution and I do not see big issues with it. With almost every MATSim update there are usually some parameters in the config file that do not work anymore and need to be updated. So the rename will not add too much work for anyone being far away from the code.

**Comment by mrieser** [comment]
> But it also causes problems in teaching, and I would vote for removing it.

which one? the `org.matsim.run.Controler`?

As Kai mentioned, originally it was thought that users can start MATSim by running `org.matsim.run.Controler`. Most likely, the `core.Controler` originally had no `main`-method, i.e. it could not be started directly, but was planned to be used for custom code. Now that it has a main-method, one could indeed remove one. Although it might break the workflow for a few users that only use releases and do not use the GUI. They would have to use a different main-class then. If that's communicated, then it's okay.

I originally liked the idea that all the classes that can be used from the outside and that have a useful `main`-method are in a `run` package. And as the `run.Controler` is very short, I don't think it adds a lot of maintenance. I think at some DeveloperMeeting we also talked about renaming `org.matsim.run.Controler` to something like `org.matsim.run.Matsim` or even `...run.RunMatsim` -- then it would still be a `run`-class, optionally even match all the `Run*Example`-classes, but hopefully no longer be confusing due to the different name.

My personal vote would go to renaming it to `RunMatsim`.

**Comment by mrieser** [comment]
> More difficult: How to deal with the controler module in the xml config. Suggestions? Maybe we could no longer accept the old spelling and write a meaningful error message.

the config could use some name-clean-up anyway (e.g. `planscalcroute`, `planCalcScore`). I already thought about adding an "alias-list" to the config-reader: We could rename the modules internally, so they will be written out in the new names, but when loading, we could do a simple lookup. It would be something like a map:

```java
Map<String, String> aliases = new HashMap<>();
aliases.put("controler", "controller");
aliases.put("planCalcScore", "scoring");
aliases.put("plancalcroute", "routing");

...
moduleName = aliases.getOrDefault(moduleName, moduleName);
...
```
One could even check if the name has changed and issue a warning in this case.

If this is of interest, we probably should discuss this in a different issue, including how the names are going to be cleaned up.

**Comment by Janekdererste** [comment]
I created an issue for the config parameter names. 

> On the Java side, this is relatively easy: Rename class, keep old class delegating everything to the new class, set old class to deprecated, wait, eventually (maybe in the far future) remove.

The Controler has a corresponding package which would be re-named as well. Should all classes in that package be kepped and delegate calls to the corresponding class in the new controller package? This would be a lot of work.

**Comment by kainagel** [comment]
`addControl(l)erListener`, `addControl(l)erListenerBinding`, ...

**Comment by jfbischoff** [comment]
>addControl(l)erListener, addControl(l)erListenerBinding, ...

I would opt to simply rename those. It will break some API, but the renaming process should not take too long.

**Comment by neuma** [comment]
We discussed this back in 2018 and came to the [following conclusion](https://matsim.atlassian.net/wiki/spaces/MATSIM/pages/112244210/Developer+Meeting+2018):

> Should we re-name the Controler?  Rename; have "Controler" return an error message.

and make it a historical site. I can't remember any serious suggestions though...

**Comment by Janekdererste** [comment]
After I forgot this issue, I will pick it up for once. After having considered all the difficulties with re-naming the ```org.matsim.core.controler.Controler``` I will just follow @mrieser s advice and rename ```org.matsim.run.Controler``` to ```org.matsim.run.RunMatsim```. 

This way, at least the confusion about multiple controllers will be solved. I hope this will help during teaching and MATSim beginners.
