### ISSUE TITLE
Copy-paste error in `EmissionsConfigGroup`

### ISSUE THREAD

**Issue by JWJoubert** [matsim-org/matsim-libs#1296]
I picked up a small copy-paste error after the consistency checking was introduced (see issue #1226). There is now a config parameter called `hbefaTableConsistencyCheckingLevel` but its [`@StringSetter`](https://github.com/matsim-org/matsim-libs/blob/47d8a52a37b0b5a181f43b84e7eba94d2d2c212a/contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java#L334) is incorrectly named `setDetailedVsAverageLookupBehavior(...)`.

Easy to fix.

As a result, there is no method available to set the consistency checking level.

**Comment by kt86** [comment]
Thanks for finding and fixing it, @JWJoubert !
