### ISSUE TITLE
Edrt and filteredSubnetwork may not work

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#1301]
I discovered a parameter combination that causes the following exception:

```
IllegalArgumentException: path and toLink are not connected. To link: org.matsim.core.network.LinkImpl@3ad9890[id=183502][from_id=25711370][to_id=234681188][length=177.62159602639377][freespeed=8.333333333333334][capacity=600.0][permlanes=1.0][modes=[drt]. Last link in path: org.matsim.core.network.LinkImpl@74d5835d[id=16570][from_id=80191499][to_id=25711370][length=98.94894314209158][freespeed=4.166666666666667][capacity=600.0][permlanes=1.0][modes=[drt]
       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)
       at org.matsim.contrib.dvrp.path.VrpPaths.createPath(VrpPaths.java:73)
       at org.matsim.contrib.dvrp.path.VrpPaths.createPath(VrpPaths.java:59)
       at org.matsim.contrib.dvrp.path.VrpPaths.calcAndCreatePath(VrpPaths.java:45)
       at org.matsim.contrib.drt.scheduler.EmptyVehicleRelocator.relocateVehicle(EmptyVehicleRelocator.java:66) 
```

The problem is only induced, if the following parameters are in charge:
•	drtConfig.setUseModeFilteredSubnetwork(true);
•	dvrpConfig.setNetworkModesAsString(“drt”);

Is anybody able to reproduce this behavior? The used test (`RunEDrtScenarioIT.java` ) is not covering the above mentioned parameter combination, which is in my point of view, for many drt scenarios the way to run, especially in combination with the new travel time matrix.

Best,
Steffen

**Comment by steffenaxer** [comment]
@michalmac

What I could investigate till now:
- This precondition is failing `Preconditions.checkArgument(path.links.get(count - 1).getToNode() == toLink.getFromNode()` within `VrpPaths` but technically are the toNode and the fromNode equal in terms of their NodeIds but not in terms of their java object id.
- This means anywhere in the code are two identical subnetworks for drt created (in term of node and link ids), but this precondition assumes that nodes are taken from the very same filtered network (same java object), which is obviously not the case

**Comment by michalmac** [comment]
Thanks @steffenaxer for your detailed report. I am looking now into it.
