### ISSUE TITLE
Remove global state from emission contrib's testing

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-libs#1302]
```TestWarmEmissionAnalysisModuleCase4``` started failing randomly after re-factoring something in the emissions contrib. I think this has to do with shared state in the test suite of this contrib in general and with the global state stored in ```HandlerToTestEmissionAnalysisModules```. I set this particular test case to ignore for now. 

**steps to remove or reduce shared state**
 - convert class members in test cases to local variables. Rather re-create those objects in every test instead of calling reset methods
 - convert ```HandlerToTestEmissionAnalysisModules``` 's counter into a private field, convert the according getter as well, create a new instance for every test method. If reset is called during test method it shouldn't be a problem since this code is guaranteed to be executed sequentially
 - remove  @Ignore from ```TestWarmEmissionAnalysisModuleCase4```

**Comment by kt86** [comment]
@GregorRyb : Can you please check, if we have done this already during the emissions tests cleanup work? If yes, this will be integrated in one of the oncoming PRs, if not, can you please fix it? Thanks, Kai
