### ISSUE TITLE
Generate WarmEmissionEvents for last link of leg

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-libs#1335]
**Current Behaviour**

Currently, no emissions are generated for the last link of a leg. The emissions for this link are generated on the next leg when the agent leaves the activity in between those two legs. 

**Desired Behaviour**

The emissions for the last leg should be generated upon VehicleLeavesTrafficEvent. When the next leg is started no emissions should be generated for that link.

**Comments**
@kt86 I discussed this with @kainagel . And we both thought this should be changed because in some cases our analysis is time dependent where it actually is important at what time the emissions are generated.

**Comment by JWJoubert** [comment]
> in some cases our analysis is time-dependent where it actually is important at what time the emissions are generated.

For what it is worth, @Janekdererste, I support this.
