### ISSUE TITLE
Failed builds on jenkins after declaring matsim-all as parent for matsim and contribs

### ISSUE THREAD

**Issue by michalmac** [matsim-org/matsim-libs#1343]
This is related to merging this PR: https://github.com/matsim-org/matsim-libs/pull/1291. The decision was to merge the PR and then fix build issues.

The list of failing jobs (as of now):
- http://ci.matsim.org:8080/job/MATSim_M2/
- http://ci.matsim.org:8080/job/MATSim_contrib_M2/

A few more jobs that are executed periodically (weekly) may also fail. Let's keep an eye on them and update the list.

**Comment by michalmac** [comment]
@marcel I hope you do not mind that I have assigned it to you?

**Comment by michalmac** [comment]
@mrieser I hope you do not mind that I have assigned it to you?

**Comment by tschlenther** [comment]
On a matsim-berlin-branch, i point to matsim 13.0-2021w02-SNAPSHOT. Travis [fails to build it](https://travis-ci.org/github/matsim-scenarios/matsim-berlin/builds/754610512). I understand from the error message that the vsp contrib points to the signals contrib which points to matsim-examples in version 13.0-SNAPSHOT which again points to  matsim-all 13.0-SNAPSHOT which can not be found.
Could this be related to this issue?

**Comment by rakow** [comment]
@tschlenther yes. But is there a reason why the vsp contrib points to a snapshot? I think that should be changed anyway.

**Comment by michalmac** [comment]
I guess this is related to specifying dependency versions using a fixed property:
```xml
<version>${matsim.version}</version>
```
instead of
```xml
<version>13.0-SNAPSHOT</version>
```

**Comment by rakow** [comment]
I was just wondering if there is a reason for it. Probably it was not intended and ${project.version} should have been used.

**Comment by michalmac** [comment]
@tschlenther Not sure if that will temporarily fix your issues, but you could try adding the unresolved dependencies to your POM. I would start with `signals`
```xml
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>signals</artifactId>
			<version>${matsim.version}</version>
			<scope>compile</scope>
		</dependency>
```
This way you should directly point to the weekly release of signals (not the snapshots).

**Comment by mrieser** [comment]
I have reconfigured `MATSim_M2` and `MATSim_contrib_M2` on Jenkins to the best of my knowledge. Let's see...

**Comment by rakow** [comment]
I think we need to make sure that the `matsim-all` pom is also published by one of the jobs, otherwise the problem of @tschlenther would persist.

**Comment by tschlenther** [comment]
> 
> 
> @tschlenther yes. But is there a reason why the vsp contrib points to a snapshot? I think that should be changed anyway.

I can not really say..
I guess that sometimes, if you change something in the vsp contrib on a wednesday for example, and you want to you use code that had been merged into matsim on tuesday, you would want the snapshot, wouldn't you?

**Comment by kainagel** [comment]
Not sure what exactly this refers to.  I assume it means the vsp contrib inside "contribs".  The contribs need to refer to matsim-SNAPSHOT, since otherwise they do not connect to the matsim one has open in the IDE.  Or am I missing something?

On 15. Jan 2021, at 13:55, tschlenther <notifications@github.com<mailto:notifications@github.com>> wrote:



@tschlenther<https://github.com/tschlenther> yes. But is there a reason why the vsp contrib points to a snapshot? I think that should be changed anyway.

I can not really say..
I guess that sometimes, if you change something in the vsp contrib on a wednesday for example, and you want to you use code that had been merged into matsim on tuesday, you would want the snapshot, wouldn't you?

**Comment by michalmac** [comment]
I added some explanation of the issue reported by @tschlenther here: https://github.com/matsim-org/matsim-libs/pull/1344#issuecomment-760968116

**Comment by mrieser** [comment]
`MATSim_M2` is green again.

**Comment by mrieser** [comment]
@michalmac: I saw that in `MATSim_contrib_M2`, you set it the maven goals to `-pl contribs -am`. But as the contribs depend on the `matsim`-module, this module will now also be built, adding quite a lot to the runtime of the job.

I had hoped that when `MATSim_M2` does a `--also-make` and `install`, that the contribs-job then would succeed without the `-am`.

**Comment by michalmac** [comment]
Good point. Skipping `-am` is also consistent with how the triggers are set up for matsim and contribs. So I am removing it.

**Comment by michalmac** [comment]
Looks like the build jobs are green again. Thanks a lot for your help with Jenkins, @mrieser !

I am closing this issue. If something else fails this week due to the recent changes in the project configuration, we can re-open this issue or create a new one.

**Comment by mrieser** [comment]
I had to adapt the weekly build this morning (and you did adapt it some more), but that should run fine in the future.

I'm still working on the code coverage for the contribs (http://ci.matsim.org:8080/view/CodeCoverage/job/MATSim_contrib_M2_CodeCoverage/). For some reasons, it still includes code coverage for matsim-core. (Build 550 still built/covered matsim-core, Build 551 didn't, but code coverage still got reported. My current guess: It didn't clean the old data in the matsim-core module, and when looking for coverage data, it found the old data, will manually clean it and rerun it)

**Comment by michalmac** [comment]
> I'm still working on the code coverage for the contribs

Thanks for the info. We also need to manually fix today's deployed weekly release (no matsim-all POM).

So I am re-opening this issue until these two things are fixed.

**Comment by mrieser** [comment]
code coverage is now back at the values from before the pom-change, so I consider this fixed.

**Comment by michalmac** [comment]
Nice. The other issue with the missing weekly-release matsim-all POM is also fixed.
