### ISSUE TITLE
No chronological order of (emission) events when using the parallelEventsManager

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#1347]
During the work on the issues with the different EventManager and processing the emissionEvents (see e.g. #1091 , #1342 , #1346 ) I found an thing, that may(?) become a problem later one:

If the single tread `EventsManagerImpl() `is used as `EventsManager`, the EmissionEvents are written at the correctly in chronological order between the other events.
![grafik](https://user-images.githubusercontent.com/12124568/104825008-65e77a00-5857-11eb-8495-a810d83aff6d.png)
--> The eventsfile is well formated.

If the `ParallelEventsManger`, which is the current default by `EventsUtils.createEventsManager(), is used instead, all emissionsEvents are add below see other events:
(Cutoutfrom the top of the file)
![grafik](https://user-images.githubusercontent.com/12124568/104825094-f6be5580-5857-11eb-8409-229047a34955.png)
(Cutout from the middle of the fileof the file: End of other events, start of emission events)
![grafik](https://user-images.githubusercontent.com/12124568/104825100-0178ea80-5858-11eb-838b-68a92d6ef7a7.png)
--> There is NO chronological order in the events file any more: neither a) between the different emission events nor b) are the emissions events integrated between the other events.

As said: I am not sure if this may lead to any problems when reading in or analyzing the events file later again. I only have in mind, that I learned a time ago, that event files (should?) have a chronological order.

**Comment by kainagel** [comment]
According to our specification, events should be chronological.  It is allowed that events within the same time step but "far apart" do not need to be chronological, but within their sequence they should be chronological.  I.e. an agent should first "leaveTraffic", then "arrive", then "leave the vehicle", then "start the activity".  But it is ok if some other agent starts with "leaveTraffic" afterwards.

Should we roll back these recent changes?  It seems to me that they may have been a bit too ad-hoc.

**Comment by kt86** [comment]
Thanks for clarifying it!  
I would vote to rollback the default from the  ParallelEventsManager to the single threaded one and then try to sort out the different issues. For slightly other reasons, this was also suggested from @rakow  in #1091 a few days ago.

**Comment by mrieser** [comment]
There should be an option for "synchronizeOnTimeStep" or similar, which might be disabled by default. This option has been around already for a while. The issue is most likely that the emission-events are created by an events-handler itself. If the handlers run in their own threads, there might be a delay between the creation of the event and the processing of the event. And thus, the newly generated emission-events are inserted at whatever time the simulation is now.
With the synchronize-feature, this should be fixable, albeit it comes with a slight performance degradation. This might also be the reason why it is switched off by default, to have a higher performance, and because events generated by event-handlers is not common in the MATSim core itself.

**Comment by kt86** [comment]
@mrieser thanks for the hint. I tried it out quickly with the `RunAverageEmissionToolOfflineExample` by using: `EventsManager eventsManager = new ParallelEventsManager(true); `

The two quick results are:
1. There is still the issue that the emissionEvents are written all together at the end of the file. 
2. Inside the events "part" it looks - without deeper analysis until now - more chronological. BUT, there are still some events in between, that are not in the correct chronological order.

--> We need to look in in more detail. And we have also to solve the `queue full` issue  (#1091) with larger scenarios. 
I have no intuition if slowing it down  (by the synchronization) would help us or if this may lead to an earlier queue full exception.

**Comment by Janekdererste** [comment]
The ```SimStepParallelEventsManagerImpl``` should do what you need. It awaits async events processing after and before every timestep. I don't know about the performance compared to the ParallelEventsManager but it is faster than using ```EventsManagerImpl``` in @kt86 's case.
```
var eventsManager = new SimStepParallelEventsManagerImpl();
```

**Comment by kainagel** [comment]
I certainly think that going away from the specification for an "unknown" performance improvement is a bad idea.  :-)

We should switch to an events handler that is according to specs.
