### ISSUE TITLE
ObjectAttributesConverter crashes with empty maps

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-libs#1348]
When ObjectAttributesConverter tries to convert an empty Map<String, String> to String it crashes. 

```
if(converter instanceof StringStringMapConverter){
				Map.Entry firstEntry = ((Map<Object, Object>) o).entrySet().iterator().next();
				if(! (firstEntry.getKey() instanceof String && firstEntry.getValue() instanceof String) ) return null;
}
```
The line which calls iterator next should check for has next I guess.

Sorry, @tschlenther I'll assign you, since you made the last changes and I'm not working for the next months :-)

**Comment by tschlenther** [comment]
> 
> 
> When ObjectAttributesConverter tries to convert an empty Map<String, String> to String it crashes.
> 
> ```
> if(converter instanceof StringStringMapConverter){
> 				Map.Entry firstEntry = ((Map<Object, Object>) o).entrySet().iterator().next();
> 				if(! (firstEntry.getKey() instanceof String && firstEntry.getValue() instanceof String) ) return null;
> }
> ```
> 
> The line which calls iterator next should check for has next I guess.
> 
> Sorry, @tschlenther I'll assign you, since you made the last changes and I'm not working for the next months :-)

yeah sure. thanks for reporting!
