### ISSUE TITLE
How to incorporate trip-level attributes for routing?

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/matsim-libs#1349]
In a project we are currently working with trip-level attributes. As one example, we are looking at defining the maximum waiting time for DRT trips individually for each trip, so it can be dependent on the person, on the time of day, on the area, etc. This is actually not so easy, because generally not a lot of information is passed down in the whole routing infrastructure.

For instance, `RoutingModule.calcRoute` only gets an origin facility, destination facility, departure time, and the person. A sensible way of defining additional attributes for a trip, is to put them in the preceding activity. Currently, we use the `Person` object with the selected plan and the `departureTime` to reconstruct the `Activity` before the trip that is to be routed in `calcRoute` based on the `departureTime`. However, this is a bit "hacky" so I am wondering what would be the clean way to pass down additional information. Some options would be:

- Pass the preceding (or maybe even both surrounding activities) to the `calcRoute` method. This is how things are mostly done in the DMC extension, but maybe in the context of `RoutingModule` / `TripRouter` this would have any unintended effects (or maybe there are good reasons to not expose the activity to the routing infrastrucutre) ?
- Pass the attributes of the preceding activity to `calcRoute`. Alternatively, have something like `<tripAttributes>` defined for each activity?
- Any other ideas?

In both cases, the relevant methods in `TripRouter` and `RoutingModule` could be extended to have additional parameters. In the activity-based case it may be wise to have two methods and deprecate the current one without the activities. The attributes-based version is less intrusive as we could have two methods with a sensible default for the current case (an empty map without any specific attributes). Still, it may be good to deprecate the current version in this case.

What does the community think? :)

**Comment by kainagel** [comment]
Still had this in my email inbox because I wanted to comment.  Looks like you have moved on in the meantime ... which is completely understandable.   I just wanted to say that we (Gregor Leich and me) had the same problem with the `routingMode` attribute that we wanted to register for each trip.  We ended up putting it into all the legs, and having routines that make this consistent between legs.  This is not great, but it had the advantage to not make a decision on the issue you are facing.
