### ISSUE TITLE
Implementation of P&R using sbb-extension

### ISSUE THREAD

**Issue by shivam-a** [matsim-org/matsim-libs#1371]
We had been working on implementing park and ride scenario in my use-case. After researching various contribs, we finally used Intermodal Access and Egress which is an advanced feature of SwissRailRaptor (SBB-extensions).  This worked fine for our approach.

However, since the model changes trips arbitrarily, it is possible a person, who has parked his car at P&R, gets again a car as a last-mile trip after using public transport. (explained in the example below). This makes sense for DRT but not in case of personal car.

Our question is it possible to have different access and egress leg modes to possibly have a walk as egress leg mode while car as access leg mode?  

For example:-

A selected plan of an agent.
![Screenshot (39)_LI](https://user-images.githubusercontent.com/49006126/107013614-dddffa80-679a-11eb-8663-a8a61b2c5782.jpg)

For the first leg of the first Home>Work trip, the access mode(M1) chosen is car but the egress mode for the third leg of the trip needs to be a different mode (M2- walk)

Similarly, for the second trip Work>Home, the access mode (leg mode from Work to PT) needs to be the same as the mode(M2) used previous half or different from the egress mode in this half (mode for second leg of this trip- M1).
@Mayoookh

**Comment by jfbischoff** [comment]
>However, since the model changes trips arbitrarily, it is possible a person, who has parked his car at P&R, gets again a car as a last-mile trip after using public transport. (explained in the example below). This makes sense for DRT but not in case of personal car.

Including it is unfortunately not quite easy, as the inbound trip does not know while routing what access mode (and to which stop) was used in the outbound trip and whether this has to be consistent.  

In our experiments we have noticed though that access and egress trips by car to and from a station usually level each other out quite reasonably. So at least in terms of traffic flow, things are roughly consistent... but probably not in terms of vehicles parked at a station. Then again, different members of a household might share a vehicle for access and egress.

**Comment by tschlenther** [comment]
One can set access and egress mode separately in the `NetworkRoutingInclAccessEgressModule`. However, this means not using the SBB-Router and requires adding a new transport mode for each intermodal combination.
For example: you could have a ptCarWalk mode where pt is the access mode to car and walk the egress mode while the pt router would still use walk for egress and access such that the result would be
walk -> pt -> walk -> car -> walk.
However, this means that an agent does not try every possible but predefined options, which is a feature that SBB-Raptor provides.

**Comment by shivam-a** [comment]
Thank you so much for your answers. I'll try the NetworkRoutingInclAccessEgressModule and see what works best.
