### ISSUE TITLE
Bug report: Carsharing crashes when initiated with an old plan containing carsharing routes

### ISSUE THREAD

**Issue by ouassimm** [matsim-org/matsim-libs#1417]
Carsharing crashes when fed an old carsharing plan with the error: `org.matsim.core.population.routes.GenericRouteImpl cannot be cast to class org.matsim.contrib.carsharing.router.CarsharingRoute`

Routes in the old plan are read as GenericRoute objects whereas Carsharing requires a CarsharingRoute object. A simple instance check + cast operation can solve this.

**Comment by ouassimm** [comment]
This fixes the problem. Carsharing tests pass with this fix.
```
if (legToBeRouted.getRoute() instanceof GenericRouteImpl){
	legToBeRouted.setRoute(new CarsharingRoute(startLink.getId(), destinationLink.getId()));
}
```

**Comment by balacmi** [comment]
Hi Ouassim,

Where is this happening?

In the main script the code located [here](https://github.com/matsim-org/matsim-libs/blob/d79b4733452f9584839016bed4e88df0bee8ffa5/contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/runExample/RunCarsharing.java#L74) is supposed to do exactly that.

**Comment by ouassimm** [comment]
First here: https://github.com/matsim-org/matsim-libs/blob/d79b4733452f9584839016bed4e88df0bee8ffa5/contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/CarsharingManagerNew.java#L80

The cast is not allowed

**Comment by ouassimm** [comment]
You can replicate the error by using your `RunCarsharing` example. Changing the input plans in the Config file to some old plans instead of the `10persons.xml` will produce the mentioned error.

**Comment by balacmi** [comment]
Hi Ouassim,

Yes, I see that. The code i pointed to is supposed to ensure that one can read in the population with carsharing trips. However the scenario has to be loaded after the carsharing route factory is set. Like this:
`final Scenario sc = ScenarioUtils.createScenario(config);
		sc.getPopulation().getFactory().getRouteFactories().setRouteFactory(CarsharingRoute.class,
				new CarsharingRouteFactory());
		ScenarioUtils.loadScenario(sc);`

I will make the change. Thanks!

**Comment by ouassimm** [comment]
Glad to help. Thank you!
