### ISSUE TITLE
Bug report: Carsharing crashes when only some agents have a CS membership

### ISSUE THREAD

**Issue by ouassimm** [matsim-org/matsim-libs#1419]
Carsharing crashes when only __a portion__ of the total population has a CS membership. The error is due to the 2nd condition in the if statement : https://github.com/matsim-org/matsim-libs/blob/825c67e807d73191775eca765dbcb7c7b294f918/contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/replanning/CarsharingSubTourPermissableModesCalculator.java#L54

A simple fix can be: 

`if (Boolean.parseBoolean(scenario.getConfig().getModule("TwoWayCarsharing").getParams().get("useTwoWayCarsharing"))
 && this.memberships.getPerPersonMemberships().keySet().contains(personId)) {
if (this.memberships.getPerPersonMemberships().get(personId).getMembershipsPerCSType().containsKey("twoway")) {
	      l.add("twoway");
}
}`

**Comment by balacmi** [comment]
Thank you Ouassim for reporting this.
