### ISSUE TITLE
No capacity set in vehicle type. There is only one seat for the driver

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-libs#1421]
I came across the following Exception running a small test case:

```
No capacity set in vehicle type. There is only one seat for the driver
```

This comes from the handling of a PT vehicle in qsim at start up [here](https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/core/mobsim/qsim/pt/TransitQVehicle.java#L42).

I believe this error is misleading as after testing it appears that a vehicle of capacity 1 is able to accept agents onboard, contrary to what this suggests.

I ran an example simulation where this `NullPointerException` was turned off and vehicles had a capacity of 1 (no standing). You can see a lot of waiting for bus vehicles (as expected), but agents are able to board eventually, showing that the single seat can be used by agents.
![ph_modestats](https://user-images.githubusercontent.com/7224053/111310887-79e00a00-8655-11eb-9198-a467530c416c.png)

Many MATSim users perform a sample (5%,10%,20% etc) and we naturally scale the PT vehicle capacities appropriately. 

This is an edge case, there are not many use cases where a vehicle of capacity 1 is reasonable but I found the error confusing as it suggests a vehicle would not be usable. I can do a PR for something more instructive if my understanding here is correct. Perhaps a warning raising a very low PT vehicle capacity has been detected.

**Comment by mrieser** [comment]
Thanks for bringing this to our attention. Originally, this error message was correct, as the vehicle capacity was adjusted for the driver. But this was changed [many years ago](https://github.com/matsim-org/matsim-libs/commit/8324dd874e436bc79827b3d558d5d7b374757e82), and this error message remained although it is no longer appropriate. We will change the code accordingly and remove this check.

**Comment by gac55** [comment]
Thanks @mrieser, sounds good. 

Feel free to close/do what you wish with this issue. I'll leave it here for now.
