### ISSUE TITLE
SupersonicOsmNetworkReader needs complete ways

### ISSUE THREAD

**Issue by phaj19** [matsim-org/matsim-libs#1432]
Hi,
I discovered that when I ran SupersonicOsmNetworkReader with incomplete ways it gives NullPointerError. 
This is not issue on its own, but it should give more reasonable error for faster debugging.
I got to this situation by running osmosis bounding box with completeWays=no (which is default).
Something like "Please obtain pbf file with completeWays=yes" could save time to potential future users.

**Comment by Janekdererste** [comment]
That’s a very good idea. You can add me as a reviewer on a pull request in case you don’t have permission to merge it on your own

**Comment by ksauzz** [comment]
@Janekdererste Hi, I tried to make [the fix](#1500). I would be happy to review it when you find time. Thanks.
