### ISSUE TITLE
ParallelEventsManager conflicts with EventsHandlingImpl when using Hermes

### ISSUE THREAD

**Issue by grauwelf** [matsim-org/matsim-libs#1442]
Hi all,

I have encountered a problem with events dumping while experimenting with a new Mobsim engine, HERMES. 
Even with the simplest scenario, I get an exception 
```java.lang.IllegalStateException: Handlers can not be added after .initProcessing() was called!```
when MATSim tries to add handler for writing down events into file. 

I looked into the code of `ParallelEventsManager` that throws this exception, and I think its logic could have been broken during rollback from `SimStepParallelEventsManagerImpl` [PR #1352 ](https://github.com/matsim-org/matsim-libs/pull/1352).

If I got it right, `ParallelEventsManager` uses field `init` to lock/unlock events processing such that no new event handlers can be added between steps 
```
eventsManager.initProcessing();
// events processing
eventsManager.finishProcessing();
```
In the earlier version of `ParallelEventsManager`, there were two fields of the similar purpose, `parallelMode` and `locked`. Now, however, `init` field is set to `false` only once, during instantiation. Then, every time `ParallelEventsManager` is initialized (on every iteration), `init` is set to `true`. 
So, when `EventsHandlingImpl` tries to add a handler for dumping events, it finds `ParallelEventsManager` in locked state and this causes the exception above.

I cannot pretend on exact understanding, but it looks like setting `init` to `false` in `ParallelEventsManager.finishProcessing()` should resolve this issue.

**Comment by bnoland** [comment]
I had the exact same issue when running the simple example configuration that comes with the MATSim example project (modified for HERMES accordingly). After examining `ParallelEventsManager.java` my colleague and I hypothesized that the issue is, in fact, precisely what @grauwelf describes above. Can a MATSim team member confirm?

**Comment by jfbischoff** [comment]
Hi, 
sorry for the late response. It is indeed a problem with the latest versions. I will fix it in the coming days and at a proper test.

**Comment by jfbischoff** [comment]
Yes, I would suggest that.
