### ISSUE TITLE
SwissRailRaptor - removing interaction activities an issue for intermodal trips

### ISSUE THREAD

**Issue by balacmi** [matsim-org/matsim-libs#1483]
### The situation

Swiss rail raptor, similarly as the traditional transit router, after creating a route, first removes all interaction activities:

https://github.com/matsim-org/matsim-libs/blob/1cd0cd7bb65e7af9fd7abfec0bf8e61cc90acf46/matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptor.java#L112

and then it fills it with pt interaction activities:

https://github.com/matsim-org/matsim-libs/blob/1cd0cd7bb65e7af9fd7abfec0bf8e61cc90acf46/matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorRoutingModule.java#L58

Now imagine a situation where we have access or egress trips, which contain their own interaction activities. These will consequently be completely lost in this process.

### Way forward
I am not sure if this procedure of removing activities and adding them back is really necessary. Could we avoid this situation and adapt:

https://github.com/matsim-org/matsim-libs/blob/1cd0cd7bb65e7af9fd7abfec0bf8e61cc90acf46/matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorUtils.java#L96

to keep the original interaction activities without removing them? Thoughts @mrieser, @jfbischoff, others?

**Comment by mrieser** [comment]
The case that an access or egress part already contains interaction activities was probably not taken into account when writing the code, and just the existing code adapted which only operated with the `legs` initially (likely inspired from the original old transit router that just created a series of legs for the stages of the trip).

So yes, this should be taken care of. I might find time for this next week at the earliest, maybe even only the week after that. So if you already have some code, feel free to create a PR.

**Comment by vsp-gleich** [comment]
I also stumbled over this and put it onto my long-term to-do list where it got lost.
Please go forward and carry over the interaction activities instead of removing and recreating them.
