### ISSUE TITLE
matsim 13 and JDK 16

### ISSUE THREAD

**Issue by michalmac** [matsim-org/matsim-libs#1521]
Since we are receiving many issues that relate to this problem, perhaps we should do something about it.

Potential actions to consider:
- fix-release Matsim 13.1 to support JDK 16 (cherry-picking #1498). Matsim 13 will live for a while and before we release Matsim 14, JDK 17 (and 18?) will become available (so the problem will grow).
- switch from Java LTS JDK (11, 17,...) to latest JDK in CI. Either for all CIs (but keeping Java version fixed at the lastest LTS) or selected CIs (like AppVeyor where we already test against the windows platform)
- increase the frequency of major releases (with GitHub Actions there are way fewer manual steps around releasing matsim).

Any opinions?

**Comment by Janekdererste** [comment]
> fix-release Matsim 13.1 to support JDK 16 

Fixing support for the latest Java Version would be nice, since selecting the correct version other than the newest available is difficult for people who are new to Java. We usually release a x.1 Version at the end of the summer semester. We could include it there. Or would you like to make a release before that date?

> switch from Java LTS JDK (11, 17,...) to latest JDK in CI

I guess this would be benefitial to detect incompatibilities. On the other hand this will also block everyone from merging things as long as eventual incompatibilities persist when the latest SDK changes. So, I think setting the Build-SDK manually and fixing possible errors would be a good option instead of automatically using the latest available one.

**Comment by michalmac** [comment]
> > fix-release Matsim 13.1 to support JDK 16
> 
> Fixing support for the latest Java Version would be nice, since selecting the correct version other than the newest available is difficult for people who are new to Java. We usually release a x.1 Version at the end of the summer semester. We could include it there. Or would you like to make a release before that date?

Nice. Nothing super urgent, so let's stick to the standard scheme for release 13.1.

> > switch from Java LTS JDK (11, 17,...) to latest JDK in CI
> 
> I guess this would be benefitial to detect incompatibilities. On the other hand this will also block everyone from merging things as long as eventual incompatibilities persist when the latest SDK changes. So, I think setting the Build-SDK manually and fixing possible errors would be a good option instead of automatically using the latest available one.

I was a bit imprecise. I am also in favour of manually bumping the JDK version in the build config. I was mainly suggesting switching from the LTS sequence (11, 17, ...) to the more fine-grained and frequent increments (11, 12, 13, 14,...).

**Comment by Janekdererste** [comment]
> I was a bit imprecise. I am also in favour of manually bumping the JDK version in the build config. I was mainly suggesting switching from the LTS sequence (11, 17, ...) to the more fine-grained and frequent increments (11, 12, 13, 14,...).

This makes sense then. It would also increase pressure to bump versions on our dependencies. Usually it is easier to increment versions in smaller steps instead of migrating from a very old release to the most recent one.

**Comment by mrieser** [comment]
As long as Java 11 is the oldest supported Java version, we should also have a build using that JDK. That means, we should build against Java 11 **and** against newer Java versions.

Running both in CI might be a bit overkill and use too much resources. In my opinion, it would be okay to have CI builds run on Java 11, and have on Jenkins a build once a week with the "latest" JDK to detect incompatibilities. Or the other way round (CI uses JDK 16/17/..., and Jenkins uses JDK 11).

**Comment by Janekdererste** [comment]
> have on Jenkins a build once a week with the "latest" JDK

I could imagine that it is easier to switch JDKs for the other builds? Since Jenkins is self hosted a new JDK would have to be installed. For the Github Actions builds only a configuration file needs to be changed.

**Comment by michalmac** [comment]
Fixed on master and 13.x

**Comment by Janekdererste** [comment]
Actually it is soon time to release version 14.0. Our MATSim class will start in April and we usually want a new release before that.

**Comment by kainagel** [comment]
Absolutely.  Let's release 14.0.

**Comment by michalmac** [comment]
- Do we have a specific timeline for that?
- I need to make sure that the github workflows are up to date. I suggest that this time the whole release process will be triggered by creating a new release on this page: https://github.com/matsim-org/matsim-libs/releases. The manual part will be limited to branching out the `14.x` branch (and updating POMs and workflows on that branch).

**Comment by Janekdererste** [comment]
Our Matsim Class will start 21st of April. This would be the deadline for a release. 

> I suggest that this time the whole release process will be triggered by creating a new release on this page: https://github.com/matsim-org/matsim-libs/releases.

This sounds very good to me. This would include 
- Making the release tag
- Making a ```14.x``` branch
- Changing the version numbers of matsim poms to ```15.0-SNAPSHOT```

In previous years releases were done by @jwilk79 . The description of how to do things is still in [Atlassian](https://matsim.atlassian.net/wiki/spaces/MATSIM/pages/185696310/How+to+deploy+a+matsim+release+to+bintray) although most of the items are irrelevant with the new workflow. What's left to do would be the items towards the end of the list such as: Updating the Website, the example project and the code-examples. I can take care or delegate to @jwilk79 .

**Comment by michalmac** [comment]
Last year @mrieser released 13.0, but it's good that we rotate the role so more of us knows a bit.

@Janekdererste Let's maybe start with updating the documentation so it reflects how we want to release 14.0. If no one objects, let's go for the semi-automated approach (using github workflows). I can start modifying the guidelines accordingly.

**Comment by Janekdererste** [comment]
I am sorry, I lost track of this issue. Yes, let's update the documentation. Can I help with this?
