### ISSUE TITLE
Agent Trajectories 

### ISSUE THREAD

**Issue by lubaso** [matsim-org/matsim-libs#1539]
I am trying to create an Event Handler to extract the agent trajectories with these attributes:

`agent_id | time | activity | event | x_coord | y_coord | link_id`

That's the output I expect:
agent_id | time | activity | event | x_coord | y_coord | link_id
-- | -- | -- | -- | -- | -- | --
1 | 0 | home | activityEndEvent | 0 | 0 | 1_2
1 | 1800 | work | LinkLeaveEvent | 10 | 10 | 2_3
1 | 1800 | work | LinEnterEvent | 10 | 10 | 2_3
1 | 2700 | work | LinkLeaveEvent | 7300 | 10 | 3_4
1 | 2700 | work | LinEnterEvent | 7300 | 10 | 3_4
1 | 3000 | work | activityStartEvent | 7300 | 25 | 4_5
1 | 24600 | work | activityEndEvent | 7330 | 25 | 4_5
1 | 24900 | leisure | LinkLeaveEvent | 7350 | 40 | 5_6
1 | 24900 | leisure | LinEnterEvent | 7350 | 40 | 5_6
1 | 78900 | leisure | LinkLeaveEvent | 14640 | 55 | 6_7
1 | 78900 | leisure | LinEnterEvent | 14640 | 55 | 6_7
1 | 79200 | leisure | activityStartEvent | 14655 | 60 | 7_8
1 | 81900 | leisure | activityEndEvent | 14655 | 60 | 7_8
1 | 82590 | home | LinkLeaveEvent | 14665 | 60 | 8_9
1 | 82590 | home | LinEnterEvent | 14665 | 60 | 8_9
1 | 136590 | home | LinkLeaveEvent | 21955 | 60 | 9_10
1 | 136590 | home | LinEnterEvent | 21955 | 60 | 9_10
1 | 139290 | home | activityStartEvent | 0 | 0 | 10_11

That's the Event Handler I created:
public class TrajectoryTemp implements LinkEnterEventHandler, LinkLeaveEventHandler {

    private Network network;

    public TrajectoryTemp(Network network) {
        this.network = network;
    }

    @Override
    public void reset(int iteration) {
        System.out.println("reset...");
    }

    @Override
    public void handleEvent(LinkEnterEvent event) {
        Link link = network.getLinks().get( event.getLinkId());
        
        System.out.println("VehId: " + event.getVehicleId());
        System.out.println("Time: " + event.getTime());
        System.out.println("LinkId: " + event.getLinkId());
        System.out.println("LinkCoord: " + link.getCoord());
        System.out.println("EventType: " + event.getEventType());
    }

    @Override
    public void handleEvent(LinkLeaveEvent event) {
        Link link = network.getLinks().get( event.getLinkId());
        System.out.println("VehId: " + event.getVehicleId());
        System.out.println("Time: " + event.getTime());
        System.out.println("LinkId: " + event.getLinkId());
        System.out.println("LinkCoord: " + link.getCoord());
        System.out.println("EventType: " + event.getEventType());
    }

}

Could anyone guide me to get the expected output?

Thank you in advance!

**Comment by Janekdererste** [comment]
I think your expected output represents what's happening in the model well. LinkEnter and LinkLeave events don't have an activity type. Since they are part of a leg, they are in between two activities. you could either use the last activity as value for this column, or have it ```undefined```.

Your event handler needs to override ```ActivityStartHandler``` and ```ActivityEndHandler``` as well if you want to print such events as well. 

Coordinates can be fetched from links like the following:

```
var link = network.getLinks().get(event.getLinkId());
var fromCoord = link.getFromNode().getCoord();
var toCoord = link.getToNode().getCoord();
var center = link.getCoord();
```
At least the activity end event also has a coord otherwise you can get this coord from the population or from the network
```
var actCoordFromEvent = actEndEvent.getCoord();
var actCoordFromLink = network.getLinks().get(actEndEvent.getLinkId()).getCoord()
var actCoordFromFacility = scenario.getFacilities().get(actEvent.getFacilityId()); // I think this works slightly different but as an idea
```

For writing CSV I'd recommend CommonsCSV https://commons.apache.org/proper/commons-csv/user-guide.html#Printing_with_headers

**Comment by lubaso** [comment]
@Janekdererste, I appreciate the feedback!
