### ISSUE TITLE
Config value for searchDistance not implemented?

### ISSUE THREAD

**Issue by phaj19** [matsim-org/matsim-libs#1546]
Hi, I thought I was using "searchDistanceOneWayCarsharing" setting in config, but it seems that the actual value is hard-coded? Shouldn't it take the value from config by default?
https://github.com/matsim-org/matsim-libs/blob/a89521e33c5c6945b8e3d0bfd3ea8dd868bb29a5/contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/CompanyAgentImpl.java#L26

**Comment by balacmi** [comment]
Thank you for noticing this. I am making a pull request with an update and some further improvements.
