### ISSUE TITLE
DrtRoute should provide the unshared ride path

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#1566]
@michalmac, in order to implement different spatial pricing mechanisms for DRT, I would like to request the link sequence of the unshared ride path, which is internally available (VrpPathWithTravelData), but not used within the DrtRouteCreator.

**Comment by sebhoerl** [comment]
Addition: The idea could be to encode the content of the DrtRoute like it is now done for the DefaultTransitPassengerRoute, i.e. a JSON object with supplementary information. This could also be optional depending on a flag (whether to provide the link sequence in the route, or not), and maybe this could also be useful for the emulation of DRT trips.

**Comment by steffenaxer** [comment]
I provided a proposal for this issue, see #1579

**Comment by steffenaxer** [comment]
PR has been merged.
