### ISSUE TITLE
MATSim rebuild error

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-libs#1575]
Hello all. 
I am getting `java: warning: source release 11 requires target release 11` error irrespective of whatever version of MATSim I clone. I tried MATSim 13, MATSim 12. I am following steps as described [here](https://www.matsim.org/docs/devguide/eclipse/). I am using Intellij and using JDK 1.8.0. I like to continue using JDK 1.8.0 as I am also using BEAM which is built upon MATSim 
Any guess what I am missing?

**Comment by Janekdererste** [comment]
The target Java Version of MATSim is Java 11. You need to compile MATSim and any project which relies on MATSim as a dependency with Java 11 or later. If BEAM's target version is Java 1.8 it can't use MATSim as a dependency. 

If you maintain BEAM, I'd suggest you migrate your application to at least Java 11. You should also consider switching to Java 17, which will be the next long term release version. It will be released in September 2021, which means that Java 11 is going to be outdated soon as well.

**Comment by vsgo222** [comment]
Thanks. this answers my question.
