### ISSUE TITLE
PRs from forks not published to maven

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#1591]
@michalmac the PR #1579 , coming from my fork has not been published automatically to our maven repository. I already talked to @mrieser and we found this error msg https://github.com/matsim-org/matsim-libs/runs/3054542711?check_suite_focus=true 

Maybe you need to adapt the configuration of the maven repository in order to allow PRs from forks.

Best,
Steffen

**Comment by mrieser** [comment]
Thanks for fixing this, I would have had no idea how to do it!

**Comment by steffenaxer** [comment]
Thanks Michal!
