### ISSUE TITLE
Allow for customized NetworkBasedTransportCosts (or provide several implementations) ?

### ISSUE THREAD

**Issue by tschlenther** [matsim-org/matsim-libs#1611]
I have seen in projects, that people use their own implementation of `NetworkBasedTransportCosts`. For example, one could think of using zones and cache the transport costs on a zonal basis. This could speed up the computation. Experiments revealed that this leads to similar results as when using the default implementation, if more than 5 iterations are run.

However, i am uncertain how easy it would be to put NetworkBasedTransportCosts behind an interface or how many code pieces in projects would break.
We should certainly discuss, though. So, what dou you think @kt86 @JWJoubert @rewertvsp ?

**Comment by kainagel** [comment]
Isn't there already an interface, which is `VehicleRoutingTransportCosts`?

**Comment by tschlenther** [comment]
Please excuse. It seems like i did not take a proper look.
When looking into the code, i saw that `NetworkRouter` needs a parameter of type `NetworkBasedTransportCosts`. However, more importantly, the `VehicleRoutingProblem.Builder` consumes `VehicleRoutingTransportCosts`. So you are right @kainagel. As a conclusion, the advice to project partners should be not to extend/rewrite NetworkBasedTransportCosts but rather implement their own `VehicleRoutingTransportCosts`. And we can think about the paramter type `in NetworkRouter.routePlan()`.
