### ISSUE TITLE
Issues of using NetworkChangeEvents

### ISSUE THREAD

**Issue by Ohay-Angah** [matsim-org/matsim-libs#1684]
Hi
I tried to change the network (~35000 links) speeds and capacities dynamically every 3 hours. My NetworkChangeEvents.xml looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<networkChangeEvents xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/networkChangeEvents.xsd">
	<networkChangeEvent startTime="00:00:00">
		<link refId="-101795_0"/>
		<flowCapacity type="absolute" value="3000"/>
	</networkChangeEvent>
	<networkChangeEvent startTime="03:00:00">
		<link refId="-101795_0_r"/>
		<flowCapacity type="absolute" value="1500"/>
	</networkChangeEvent>
	<networkChangeEvent startTime="06:00:00">
		<link refId="-101795_1"/>
		<flowCapacity type="absolute" value="2000"/>
	</networkChangeEvent>

        <networkChangeEvent startTime="00:00:00">
		<link refId="-101795_0"/>
		<freespeed type="absolute" value="26.8"/>
	</networkChangeEvent>
	<networkChangeEvent startTime="03:00:00">
		<link refId="-101795_0_r"/>
		<freespeed type="absolute" value="31.3"/>
	</networkChangeEvent>
	<networkChangeEvent startTime="06:00:00">
		<link refId="-101795_1"/>
		<freespeed type="absolute" value="22.3"/>
	</networkChangeEvent>
</networkChangeEvents>
```

With the file input, the error `Expected number of change events (1) differs from the number of events found (0)!` popped up.

It seemed like inside the core codes, the `ChangeValueGetter` couldn't recognize the `flowCapacity` events while the `freespeed` events worked fine. I went through all the issues and followed every suggestion with no luck. So I attached the log file here to see if anyone could help

Thanks for your time!
[logfile.log](https://github.com/matsim-org/matsim-libs/files/7233547/logfile.log)

**Comment by CLIVTI** [comment]
i had the same problem before and then i found that the reason is that you have 2 network change events modifying the same link at the same time. for instance, one network change event changes link i's capacity to X at time t, while another one changes link i's capacity to Y at time t.

**Comment by Ohay-Angah** [comment]
Thanks for your suggestions, @CLIVTI. I got a follow-up question, if you can only change single event (speed or capacity) at a time, how do you calibrate the speed and capacity if you'd like to calibrate bother of them each hour?

**Comment by CLIVTI** [comment]
Hi, it should be fine if you change both speed and capacity at the same link and same time. One example using code but not xml file to specify such would be:

NetworkChangeEvent networkChangeEvent = new NetworkChangeEvent(YourTime) ;
		networkChangeEvent.setFlowCapacityChange(new ChangeValue( ChangeType.ABSOLUTE_IN_SI_UNITS,YourCapacity));
		networkChangeEvent.setFreespeedChange(new ChangeValue( ChangeType.ABSOLUTE_IN_SI_UNITS,  YourSpeed));
		networkChangeEvent.addLink(YourLink);
		NetworkUtils.addNetworkChangeEvent(yourNetwork,networkChangeEvent);

what you cant do is to change flowCapacity or speed at same time same link. For instance, the following is wrong:

NetworkChangeEvent networkChangeEvent1 = new NetworkChangeEvent(YourTime) ;
		networkChangeEvent1.setFlowCapacityChange(new ChangeValue(ChangeType.ABSOLUTE_IN_SI_UNITS,YourCapacityValue1));
		networkChangeEvent1.addLink(YourLink);
		NetworkUtils.addNetworkChangeEvent(yourNetwork,networkChangeEvent1);

NetworkChangeEvent networkChangeEvent2 = new NetworkChangeEvent(YourTime) ;
		networkChangeEvent2.setFlowCapacityChange(new ChangeValue(ChangeType.ABSOLUTE_IN_SI_UNITS,YourCapacityValue2));
		networkChangeEvent2.addLink(YourLink);
		NetworkUtils.addNetworkChangeEvent(yourNetwork,networkChangeEvent2);

**Comment by Ohay-Angah** [comment]
After several days of coding up and testing, it finally works. Before getting your answers, I was following [this](https://github.com/matsim-org/matsim-code-examples/issues/383#issuecomment-655333551) to configure my network change events and realizing that doesn't work for my case.

Stepping on your guide, I found that the order of features matters. If I put `freespeed` first followed by `flowCapacity`, it gives me errors with a "null" result saying that the setting's not as expected. It seems to me that the order should always be `flowCapacity` at first and `freespeed` after. 

Applying the same idea to the XML setting, I put `flowCapacity` before `freespeed` in the same event of the same link, concluded as follows, and it finally also worked. Note that I'm using the 0.10.0 version.

````
<networkChangeEvent startTime="6:00:00">
	    <link refId="1"/>
	    <freespeed type="absolute" value="10.0"/>
	    <flowCapacity type="absolute" value="20"/>
	</networkChangeEvent>

<networkChangeEvent startTime="6:00:00">
	    <link refId="2"/ >
	    <freespeed type="absolute" value="22.2"/>
	     <flowCapacity type="absolute" value="60"/>
	</networkChangeEvent>
	
</networkChangeEvents>
````
Thanks for your useful [answers](https://github.com/matsim-org/matsim-libs/issues/1684#issuecomment-934736614)!
