### ISSUE TITLE
Why are properties of reverse links in bicycle network hard coded?

### ISSUE THREAD

**Issue by marecabo** [matsim-org/matsim-libs#1722]
The [OsmBicycleReader](https://github.com/matsim-org/matsim-libs/blob/master/contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/OsmBicycleReader.java) reads an OSM file and creates a bicycle network. It creates a reverse link for every link. However, the properties (`freespeed`, `capacity`, `numberOfLanes`) of this reverse link are hard-coded (see below) and not taken from the the original forward link. 

https://github.com/matsim-org/matsim-libs/blob/12c72bde619b57a4a38eb39620515d4df062cfde/contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/OsmBicycleReader.java#L111-L114

**Example**

```java
Link F: 
org.matsim.core.network.LinkImpl@34fcaaad[id=9061489540000f] 
[from_id=331253128] 
[to_id=528518222] 
[length=2.2922350263730866] 
[freespeed=2.7777777777777777] 
[capacity=600.0] 
[permlanes=1.0] 
[modes=[car, bike]

Link R: 
org.matsim.core.network.LinkImpl@6bd94f9d[id=9061489540000f_bike-reverse]
[from_id=528518222]
[to_id=331253128]
[length=2.2922350263730866]
[freespeed=8.333333333333334]  // <-- way faster than forward link?
[capacity=375.0]  // <-- why less capacity?
[permlanes=1.0]
[modes=[bike]
```

**Expected Behavior**

I would expect, that all properties should have been used from the forward link, if a reverse link is added at all, as the length is already taken from the forward length.

Could you shed some light on the reasoning for using hard-coded properties for bike reverse links? On first glance I would expect at least freespeed to be the same, and capacity maybe less if the reverse link enables driving in the wrong/not permitted direction, but that might be hard to detect in the general case.

Thanks for your response and all your work on MATSim!

**Comment by marecabo** [comment]
Hi, thanks for your explanation. 

It took me a while, but I was looking at the code with a single-mode network in mind, in that case, I expected bikes to have the same freespeed in both directions. 

With a multimodal network with car and bike, it makes sense to me, to leave the freespeed for the shared forward links as is, to not increase the frespeed for cars as well.

**Comment by steffenaxer** [comment]
May we close this issue?
