### ISSUE TITLE
Changes in NetworkUtils regarding time invariant networks are too complicated

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-libs#1751]
I think these changes were introduced by @sebhoerl and @luchengqi7 . 

While tinkering with time variant networks you changed the signature of some Network related methods. I think these changes introduce too much overhead for such a special case. For example:

```NetworkUtils.createNetwork``` used to create an empty default network. The signature has now changed to ```NetworkUtils.createTimeInvariantNetwork()``` while the old Method name was changed to: ```NetworkUtils.createNetwork(NetworkConfigGroup networkConfigGroup)``` I think you should have chosen another approach by leaving the old signature as is and introducing a new method with the config group parameter. (Or overload the ```createNetwork``` method. I think you should have done so, because my guess is that most of the people are happy with the default network without config parameters. Therefore this method name should be the most simple and short one. 

```NetworkUtils.getCollector()``` was meant to be used as the finishing statement of a stream working with a network. Due to the changes described above this method has now two overloads with either ```Config``` or ```NetworkConfigGroup```. The network config group is then stored in the collector, only to be passed into the more complicated ```createNetwork``` method. I think this method should either have no arguments or at least, if you think you really want to pass configuration parameters into it, have a default version without parameters, which creates the collector like the following 

```
	public static NetworkCollector getCollector() {
		return new NetworkCollector(ConfigUtils.createConfig().network());
	}
```

Apparently this is the case for many other ```NetworkUtils``` methods as well. Maybe we can discuss whether time varian networks are important for everybody and whether this should surface so prominently in the API.

**Comment by sebhoerl** [comment]
It is fine for me to change it back. At the end I went for it after a couple of months without comments on the initial issue :) 

My thinking was the following: The network creation stuff is being used in many multipurpose and convenience methods. Not making this time-variant property explicit, however, lead to often losing (unconsciously) the network change events as it happened internally inside DRT when filtering for the modal subnetwork. The result was that predefined network speeds were not considered by DRT, but the standard free speeds.

But maybe, in the long-term, the whole structure of saving the events inside the `Network` is not ideal. One would probably just need the network as a plain data object and then have some interfaces to get the free speed, capacity, lanes, etc. at any time of the day. And then there would be a default implementation that gets it from the network attributes, while another one would first look up the change events and then fall back to the attributes.

**Comment by Janekdererste** [comment]
I am very sorry to have missed the initial issue. 

A simple thing to do now would be to re-instantiate the old signatures which would then call the explicit versions of the same method with default values. (That's what I did at least in the downstream projects I own) This way one would not have to re-factor everythin again, but it would be still possible to use the simple signatures from the outside. Would this still serve your intention?

I wasn't aware that Network-Change-Events are stored within the network. I guess, because I have never worked with this feature.

**Comment by sebhoerl** [comment]
Yes, that sounds good
