### ISSUE TITLE
Relax unoccupied custom task constraints for dvrp?

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/matsim-libs#1760]
The VehicleOccupancyProfileCalculator assumes that tasks are either 
a) passenger serving tasks
b) non-passenger serving tasks

In consequence, passenger serving tasks will _always_ be labeled as 0 pax/1 pax/ etc.:
https://github.com/matsim-org/matsim-libs/blob/6b038c562bb17bd4a4cbd7c29bed797fd12b3458/contribs/dvrp/src/main/java/org/matsim/contrib/util/stats/VehicleOccupancyProfileCalculator.java#L155-L162

In the shifts extension, we added relocate for shift changeover / relocate for shift break tasks to operational facilities such as hubs. We would like them to show up individually in the occupancy profiles so we set them as non-passenger-serving tasks. However, in our implementation, drivers may still serve rides on their way to the hub if the detour is acceptable. In this case, the code quoted above fails with an exception since passengers are not allowed during such tasks. Our current "quick fix" is to set these tasks as passenger serving tasks in the DrtModeAnalysisModule - however, now we do not see them in the occupancy plot anymore:

https://github.com/matsim-org/matsim-libs/blob/6b038c562bb17bd4a4cbd7c29bed797fd12b3458/contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/run/MultiModeShiftDrtModule.java#L33-L41

Could we maybe relax this constraint and allow passengers to be on (user-definable) non-regular passenger serving tasks as well?

**Comment by michalmac** [comment]
It's hard to mix vehicle occupancy with task types in a consistent way on a 2D plot as these are 2 separate dimensions. So either you lose some information on the vehicle occupancy or on the relocation tasks, which means the values on the plot are not reliable.

What if there was a separate chart that shows currently executed task types (instead of vehicle occupancy)?

**Comment by sebhoerl** [comment]
Yes, somehow two different plots seems like a good idea?

**Comment by nkuehnel** [comment]
Sometimes the simplest solutions are the best - you are absolutely right, it would be much cleaner. If no one is already working on such analysis I will try to add one in the next days

**Comment by michalmac** [comment]
@nkuehnel I haven't started working on it, so please go ahead. It would be great if you could add it to dvrp (so it could be used both in drt and taxi).

BTW. In the past we had something like this for taxis: https://github.com/matsim-org/matsim-code-examples/issues/659#issuecomment-986062781 (chart 1), but I had to remove it as the chart was created from vehicle plans (postprocessing) - very old design, while currently all stats are calculated from events.
