### ISSUE TITLE
output_trips.csv.gz does not contain stuck and aborted trips

### ISSUE THREAD

**Issue by ksauzz** [matsim-org/matsim-libs#1767]
Hi,
I noticed output_trips.csv.gz doesn't contain trips which got stuck and aborted at the end of simulation.
I'm not sure it's intentional or not, however It's good to my use-case that the file includes stuck trips.

**Comment by vsp-gleich** [comment]
Hi, this is rather hard to implement (trips.csv is based on events and those are hard to merge with plans) so we decided not to implement it. If you need that information you can write your own analysis comparing plans.xml (all trips including the incomplete ones) and trips.csv (excluding the incomplete trips -> identify the missing incomplete ones).

**Comment by ksauzz** [comment]
Thank you for the explanation and the quick response. I understood the team decision. I will try to make a tool to handle it. :smiley:
