### ISSUE TITLE
output_experienced_plans is missing location for first activity

### ISSUE THREAD

**Issue by akay-arup** [matsim-org/matsim-libs#1804]
Hi there. We've found that the output files for experienced plans are missing the `x` and `y` attributes for each agent's first activity.

For example, the first two activities from a single agent's experienced plan (excluding the legs) might look like:
```xml
<activity type="home" link="12079" end_time="06:40:00" > </activity>
...
<activity type="escort_education" link="5215389694052390667" x="703097.0" y="808671.0" start_time="06:53:40" end_time="07:09:37" ></activity>
...
```

However, the location **is** included in the "planned plans" (i.e. `output_plans.xml`) file for those activities.

Is there a particular reason this information is being redacted from the experienced plans?

**Comment by jfbischoff** [comment]
Thanks for reporting, that is a funny bug. Facilities and links are provided, but not the coordinates. I will fix it in the upcoming days.
