### ISSUE TITLE
Put in roadType attributes for emission calculation when creating the network?

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#1823]
Hi at all,

we (at VSP) will go more and more forward to make the emission calculation a standard analysis, which should be used as often as possible. For this, one needs the roadType set as an attribute for each link.

Currently, we are doing this ex-post after the simulation run, when starting the emission analysis. This has at least three disadvantages:

1. One has to change the `output_network.xml` and it is not documented in any file, which assignment of `roadType `was made for the analysis. --> Without the analysis script, the analysis is not reproducible.
2. The run script is a constant copy&paste work, which will go into more and more repositories... With each reproduction (and small adaption) we increase the probability, to do there any chances (un)intentionally, which then will spread further.
3. We are guessing the correct type by the number of lanes and the speed limit. In (semi) old networks, there is also no information from OSM available, which may help for a better assignment. (I know, that this is not done consistently in OSM as well: What is a motorway?)

--> Even if the OSM data is available now in more and more cases (see 2.) , I am wondering if one should do the tagging with the` hbefa roadType` in the links attribute when building up the scenario (creating the network for the scenario). Then it is available as input for the emissions analysis and is already there in all runs of the scenario, which helps to do consistent analyses. (A)

Another idea was to put some preprocessing in the emissions contrib which will do that assignment of roadTypes to the untyped network. (B) 
In my opinion, (B) has - besides the advantage that is done every time exactly in the same way - the disadvantage, that it is done independently of the local characteristics and knowledge (which should be there by the people who are building up a new scenario). Such a method can still also implemented for all people who want to have some "default" alternative(?) and to use it for older networks/scenarios.

@Janekdererste As said today, let's have some discussion about it.
@all: Please give us your thoughts :)

**Comment by Janekdererste** [comment]
I am happy to do it. My suggestion would be the following:

- Put the OSM-Road-Type as well as the allowed Speed from OSM into the network as standard link attribute
- Guess the HBEFA Raod type from those attributes as pre-processing in the emissions contrib.
- Provide an option to have HBEFA road types proviede by the emission contrib user
- Fail if neither OSM nor HBEFA road types are provided

This way, assumptions about emission calculations won't spill into our osm package.

**Comment by JWJoubert** [comment]
I vote for any approach where the software makes as little as possible _guessing_. If you want to use the `emissions` contrib, then you ought to be aware of the scenario building process (network creation and the required link attributes). 

It will be helpful if the (agreed upon) link attribute name could be an `enum` in, for example, `EmissionUtils` or the `EmissionsConfigGroup` classes.

**Comment by JWJoubert** [comment]
Very nice example, thanks @Janekdererste. We did something similar for our South African scenario(s).

**Comment by kt86** [comment]
Thanks @Janekdererste for taking care / doing it :)
And thanks @JWJoubert for bringing in your thoughts and expertise.

@kainagel and I prefer adding the hbefa tags very early in the process of a simulation run. This has also something to do with the 
> If you want to use the `emissions` contrib, then you ought to be aware of the scenario building process (network creation and the required link attributes)

It happens now more and more, that the person who is using a network, does not know a lot of generating/creating it.


Because we are going forward, that we want to have the emission analysis as standard output after the last iteration, it makes sense to ensure that we _have all information available already when starting the run_. 

So _my suggestion_ is, to create a method e.g. in `EmissionUtils`(or NetworkUtils ?) that can make this assignment / guessing with some default values. The best would be both: a method for creating i) from OSM tags and  ii) the guessing approach from above. 
But I am not sure if I would like to have it inside the running pipeline of the emission contrib, because that would be in the end another piece of automagic, where no one is aware of the details of the current network.

Following this suggestion / idea, one could put in a check to the `emissions contrib`, which will trow an exception _before the first iteration_ if one of the following requirements is not fulfilled: 
i) all links have a valid hbefa string (maybe a second good reason for having it as enum?)
ii) all vehicles have the engine information set.

So the user has two options: Either not doing the emissions analysis OR preparing the input data as needed. Which seems to be something more straight forward for me :)

**Comment by Janekdererste** [comment]
Alright, I have dug into the code and apparently there already is infrastucture for this. The contrib has an abstract ```HbefaRoadTypeMapping``` class. Currently it has three concrete implementations

- ```OsmHbefaMapping```
- ```VisumHbefaRoadTypeMapping```
- ```LinkHbefaMapping``` which is never used

The former two are used in the ```EmisionModule``` themselves. When ```EmissionConfigGroup.hbefaRoadTypeSource``` is either ```fromOsm``` or ```fromFile``` one of the two is used. 

Since we want to reduce complexity and automagic in the EmissionsContrib, I would now 

- remove the implicit convertion of link attributes as well as the config switch
- make the interface as well as the mappers public, so that they can be used from outside
- Change the ```OsmHbefaMapping``` so that it works with the default Osm-Attributes from our Osm-Network-Converter
- add a check with a (hopefully meaningfull error message) to the startup of the ```EmissionModule``` which checks all links for Hbefa Attributes
- add an additional ```VspHbefaMapper``` which takes our guessing code into the contrib. 
- Remove the ```LinkHbefaMapping``` since it is not used and trivial

This way, having the correct road types is not part of the ```EmissionModule``` any more. I think this would be analogue to the VehicleInformations. However, users can start with one of the built in mappings and still provide their scenario specific road type mappings themselves if desired.

**Comment by kt86** [comment]
Without having a detailed look into  it / the code:

The approach sounds to me like a reasonable way to go. :) 
For not breaking existing code, I suggest deprecating the previous ConfigParameter: `EmissionConfigGroup.hbefaRoadTypeSource` and adding helpful error message  instead  of removing it directly... (?)

And please try to avoid to use hat lazy "var" ... this makes it not easier to for me and in some month / years after some more refactorings, the name of the variable is maybe misleading. For this case, it helps, if the type is written explicitly.

**Comment by Janekdererste** [comment]
> I suggest deprecating the previous ConfigParameter

Did exactly that. 

> And please try to avoid to use hat lazy "var" 

I will not use it just for you 😘
