### ISSUE TITLE
Automatic checks are failing due to missing file

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#1841]
The checks in #1840 are currently failing.

There seems to be a problem after java jdk has been downloaded. Looks like java is missing or not correctly extracted:
`Run mvn install --batch-mode --also-make --projects contribs/vsp -DskipTests -Dsource.skip
/usr/bin/mvn: 194: exec: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.1-12/x64/bin/java: not found
Error: Process completed with exit code 127.`

@mrieser or @michalmac maybe you might have a look.

Best,
Steffen

**Comment by steffenaxer** [comment]
Seems to be fixed by itself 😀

**Comment by michalmac** [comment]
Yes, looks like a temporary GH Actions issue.
