### ISSUE TITLE
Perhaps there are some unnecessary code?

### ISSUE THREAD

**Issue by luchengqi7** [matsim-org/matsim-libs#1918]
It seems that we are having some strange operation here:
something like x = a + b - a. Is there any particular reason for doing this? And also we are setting the travel time for a leg twice with the same value.

https://github.com/matsim-org/matsim-libs/blob/7c302f888f49efecbc28a9ff0edcc1879f835ee8/matsim/src/main/java/org/matsim/core/scoring/EventsToLegs.java#L268

https://github.com/matsim-org/matsim-libs/blob/7c302f888f49efecbc28a9ff0edcc1879f835ee8/matsim/src/main/java/org/matsim/core/scoring/EventsToLegs.java#L269

**Comment by kainagel** [comment]
Something like this might have come from automatic refactoring, e.g. when `leg.getArrivalTime` was automatically replaced by `leg.getDepartureTime + leg.getTravelTime`.

Minimally please leave a Java comment.  Or modify and run all tests.  A challenge is that
```
double travelTime = leg.getTravelTime().seconds()
```
is not exactly the same as the above in cases where `leg.getDepartureTime` is something weird (e.g. NaN, infinity, or throwing an exception).  So, unfortunately, one might get a different result in corner cases.
