### ISSUE TITLE
DRT: Discrpency between coordinates regarding the boarding place

### ISSUE THREAD

**Issue by luchengqi7** [matsim-org/matsim-libs#1941]
Under the door2door operation scheme, the coordinate of the boarding / deboarding location of the DRT trips are on the middle of the link (**output events**, **output plans**). The calculation of the walking time and the actual request submission time is based on the distance between the request original location and the toNode of the link. 

This can cause some confusion during the de-bug process. Perhaps we can try to fix it?

![截屏2022-04-10 16 35 54](https://user-images.githubusercontent.com/43133404/162624617-1ec7dd4e-6c5a-4f6c-9289-2213a42ec09d.png)

**Comment by kainagel** [comment]
It is, unfortunately, quite difficult to fix in a way that is also consistent in the long term.  In the end, one always has to admit that the current MATSim resolution is not higher than link level.  Having said this, there seem to be the following statements and resulting thoughts:
1. In the "full" matsim data model, activities happen at facilities, which have arbitrary coordinates.
2. (In the "full" matsim data model, there is also something like offsetToNode, to denote how far along the link something happens.  This, however, is used only at very few places; see, e.g., the 'VehicleEnters/LeavesTrafficEvent'.)
4. What is thus needed is a connection from the facility coordinate to the link.  On the link, the agent does something like enter her/his own parked vehicle, board a bus, or board a DRT.
5. The initially most plausible option is to walk to the toNode of the link.  This is quite possibly also the most plausible option for bus or DRT.
6. However, for a parked individual car this is _not_ the most plausible option.  Here, one could say that instead one should use the orthogonal distance to the link as walking distance, and then "implicitly teleport" the person to the end of the link.  This would say that individual cars are typically parked in front of the facility, and the parking facilities at the end of the matsim link are just a consequence of the reduced resolution data model.  (The fact that this would make the car trip shorter would be compensated for by making it correspondingly longer at the destination.)

Also note that bus stops also have coordinates, which are not necessarily consistent with the above.

I fear that to resolve this, we would need mode-specific configuration options.  And for each mode, one would minimally need what we have used to far (toMiddleOfLink) and whatever is now newly implemented (toEndOfLink).  Also, I am not sure where this would go.  At first glance, it feels like `PlansCalcRouteConfigGroup`, but at second thought I am not so certain: The mobsim would be the first module which would have to get this right.  Implying (a) mode-specific configuration options, which is something that we have avoided so far.  And (b) implying that the router would have to look into the qsim config options (not terrible, but so far not necessary).

Note that there is also `AccessEgressType` in `PlansCalcRouteConfigGroup`.  Right now I think that these two things are orthogonal, but this may not hold.

I think that @luchengqi7 and I should look into this together at one of our next meetings.  Until then, further comments and experience reports welcome.
