### ISSUE TITLE
How to use drt speed up system

### ISSUE THREAD

**Issue by 14841484** [matsim-org/matsim-libs#1966]
Hi.
I have a question about drt speed up system.
I found the drt speed up module(https://github.com/matsim-org/matsim-libs/tree/master/contribs/drt/src/main/java/org/matsim/contrib/drt/speedup), but I do not understand how to use it.

Please tell me speed up system.

**Comment by vsp-gleich** [comment]
Hello, inside your drt config group you have to add the respective _speed-up_ parameter set (just like drt-fare parameter set), e.g.:

	<module name="multiModeDrt">
		<parameterset type="drt">

... _other parameters_ ...

			<parameterset type="drtSpeedUp" >
				<param name="fractionOfIterationsSwitchOn" value="0.0" />
				<param name="fractionOfIterationsSwitchOff" value="0.99" />
				<param name="intervalDetailedIteration" value="25" />
				<param name="initialWaitingTime" value="600.0" />
				<param name="initialInVehicleBeelineSpeed" value="4.16667" />
				<param name="waitingTimeUpdateDuringSpeedUp" value="Disabled" />
				<param name="movingAverageSize" value="2" />
			</parameterset>
		</parameterset>
	</module>
