### ISSUE TITLE
Carrier capabilities not complete in XML

### ISSUE THREAD

**Issue by JWJoubert** [matsim-org/matsim-libs#1987]
Hi @kt86 and @rgraebe 

Instead of using example files, we are trying to create the required input files for the `freight` contrib. Specifically when a `Carrier` has a an infinite fleet size. According to me, if the `CarrierCapabilities` is set to `CarrierCapabilities.FleetSize.INFINITE`, then one only needs to specify the `VehicleType`s and not the actual vehicles. Yet, when writing the carrier to file, I get something like
```
<capabilities fleetSize="INFINITE">
	<vehicles>
	</vehicles>
</capabilities>
```

with no vehicle types written. For me this will lead to trouble down the road in terms of reproducibility. Can/should we fix this? Do you agree that this is problematic? Am I missing another use case? I am happy to go ahead and work on it and tag you in a pull request.

**Comment by kt86** [comment]
Dear Johan, 

thanks for pointing this out!

We are also using the INFINITE fleet size for our simulation, so it is relevant for us as well! (Even if I have not seen this before, but I run the last things from already existing .xml files...)

Just for clarification: What we are doing, is that we need to define one vehicle per depot (and vehicle type) as representative for this vehicle type. -> It is still a definition of (at least) one vehicle, which then stands for many vehicles of the same type at the same location.

Can you share the code snippet, you are using? 

I totally agree, that this should be written out! -> We need to fix it, if it is missing. So please go ahead and add me as reviewer. I will be off for some days during the next two weeks, but I will try to come back to you as soon as I can.

Another quick thought: I know that @kainagel changed something, that is related with the loading of the vehicleTypes to the carrier a few months ago (part of #1849). Maybe that is somehow relevant here ???

**Comment by JWJoubert** [comment]
> Another quick thought: I know that @kainagel changed something, that is related with the loading of the vehicleTypes to the carrier a few months ago (part of https://github.com/matsim-org/matsim-libs/pull/1849). Maybe that is somehow relevant here ???

Indeed, I believe it might be relevant, @kt86. There are tests commented out, but without clear design decisions. The XML written is not the same as the XML read (there are warnings of ignored fields, like `route`) - there is no document type specified. I do not want to undo changes that had explicit design decisions behind them, but currently it is really hard to navigate the code. There are warnings (in the logger) of deprecated code, yet the code is not tagged as `@Deprecated`.

... and, specifically, the `VehicleType`. This appears in the log

> 2022-05-17 14:33:36,975  WARN CarrierVehicle$Builder:109 .setTypeId has no functionality anymore and is deprecated

Okay, so this then answers my question. The code is usable, but needs to be tagged as _deprecated_.
