### ISSUE TITLE
ShpOptions.getGeometry() only reads first feature of shp

### ISSUE THREAD

**Issue by simei94** [matsim-org/matsim-libs#2003]
When using the getGeometry() method of the contribs/application/src/main/java/org/matsim/application/options/ShpOptions.java class, only the first (or one) feature is read. If I want all the features to be read, I have to iterate over the features myself, although the method should do this already..

**Comment by Janekdererste** [comment]
Looking at the code of `ShpOptions` it looks like it is doing exaclty what you want. 

```
/**
	 * Return the union of all geometries in the shape file.
	 */
	public Geometry getGeometry() {

		Collection<SimpleFeature> features = readFeatures();
		if (features.size() < 1) {
			throw new IllegalStateException("There is no feature in the shape file. Aborting...");
		}
		Geometry geometry = (Geometry) features.iterator().next().getDefaultGeometry();
		if (features.size() > 1) {
			for (SimpleFeature simpleFeature : features) {
				Geometry subArea = (Geometry) simpleFeature.getDefaultGeometry();
				geometry.union(subArea);
			}
		}
		return geometry;
	}
```
This gets the union of all the features geometries right?

The [test class](https://github.com/matsim-org/matsim-libs/blob/master/contribs/application/src/test/java/org/matsim/application/options/ShpOptionsTest.java) for this class doesn't have a test case for this methdo. You could start by adding a test case and see whether it works or fails.

**Comment by simei94** [comment]
Exactly, but somehow only the first feature is used and not all of them as a union. This occured multiple times already and not only in my own scripts..

**Comment by Janekdererste** [comment]
Well, then it is probably a good idea to verify correctnes of the library with a unit test before investigating your project set ups ;-)

**Comment by Janekdererste** [comment]
Closing this, because the autoclose in the pr didn't .
