### ISSUE TITLE
How to change link allowed modes dynamically? Using NetworkChangeEvent?

### ISSUE THREAD

**Issue by FrankHuang777** [matsim-org/matsim-libs#2088]
Hello, all!

I know NetworkChangeEvent can help change the flowCapacity, freespeed and lanes of specified links during simulation by using networkChangeEvents.xml or writing some code, like the following shows:

```
<?xml version="1.0" encoding="UTF-8"?>
<networkChangeEvents xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/networkChangeEvents.xsd">
	<networkChangeEvent startTime="03:00:00">
	    <link refId="1"/>
	    <link refId="2"/>
	    <link refId="3"/>
	    <freespeed type="absolute" value="1.0"/>
	</networkChangeEvent>
</networkChangeEvents>
```

```
NetworkChangeEvent networkChangeEvent = new NetworkChangeEvent(3*3600);
Link link1 = scenario.getNetwork().getLinks().get(Id.createLinkId("1"));
networkChangeEvent.setFreespeedChange(new NetworkChangeEvent.ChangeValue(NetworkChangeEvent.ChangeType.ABSOLUTE_IN_SI_UNITS, 1));
networkChangeEvent.addLink(link1);
NetworkUtils.addNetworkChangeEvent(scenario.getNetwork(), networkChangeEvent);
```

In my project, I need to change the link allowed modes dynamically.
For example, link 1 allowed car and pt
`<link id="1112" from="11" to="12" length="1200.00" capacity="2000" freespeed="12" modes="car, pt" permlanes="1" />`
I want to make link 1 pt only, i.e. modes="pt" from 7am to 9am, what should I do?

Thanks!

**Comment by JWJoubert** [comment]
Hi @FrankHuang777, an undergraduate student of mine, @rgraebe did something similar for the high-occupancy vehicle (HOV) lane on the [N2 freeway in the City of Cape Town](https://www.google.com/maps/@-33.9573173,18.5471865,3a,75y,285.23h,87.8t/data=!3m6!1e1!3m4!1sUttXBdrESJvDOzFtg4h_ug!2e0!7i16384!8i8192) (I hope the street view link works).

Anyway, the approach we followed is the following:
- for every link `AB` (3 lanes in our case) that is in an HOV lane, duplicate it, `AB_hov`;
- `AB` is allowed all modes and `AB_hov` is *_only allowed `pt`_* as mode;
- during the times that the HOV lane is operational, make the number of lanes (using `NetworkChangeEvents`) of `AB` 2 and that of `AB_hov` 1;
- when HOV period has ended, change the number of lanes back to 3 for `AB` and to 0 for `AB_hov`.

Did I get that right, @rgraebe? The only unintended consequence is that I cannot remember what happens to agents when they find themselves still on `AB_hov` when its number of lanes become zero again. Maybe @rgraebe can chip in.

**Comment by FrankHuang777** [comment]
Thanks @JWJoubert , I think it is a very clever way to achieve the effect I want. I will check what will happen to vehicles when the number of lanes goes to zero, perhaps they will be stuck.

I'm also trying to extend NetworkChangeEvent to support more dynamic changes to link attributes, but that's a bit difficult for me. 😂

Thanks again for your help!

**Comment by FrankHuang777** [comment]
Thank you @rgraebe , I think I have achieved the effect I wanted without using NetworkChangeEvent.

In fact, I study the scenario of traffic restrictions based on the last digit of license plate numbers. This means I need to ban certain vehicles at certain times and on certain roads depending on their license plate number. 
I achieve this indirectly by increasing the time required for the restricted vehicle to pass on the restricted road. The only thing I do is modifying [TravelTimeCalculator](https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeCalculator.java).

Thanks for your advice!
