### ISSUE TITLE
Question: In LinkProperties under osm reader, why is the capacity of short roads doubled

### ISSUE THREAD

**Issue by akvalvaag** [matsim-org/matsim-libs#2129]
I am having trouble finding any documentation on why the capacity of a link is doubled if it is shorter than 50m.

Does anyone know why it is doubled, and why its 50m?

https://github.com/matsim-org/matsim-libs/blob/97f655596ca6961d12f268cde1bec9bd0389ce85/contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/LinkProperties.java#L30-L33

**Comment by Janekdererste** [comment]
We found that short road pieces in intersections and roundabouts didn't have enough capacity in the simulation and posed unwanted bottlenecks. 

Therefore we just increased the capactity. 50m is an arbitrary threshold we chose to be sure to catch most cases.

**Comment by akvalvaag** [comment]
Ah, I see. Thank you for the answer!
