### ISSUE TITLE
Freight: Add tests for new Carrier*Reader/Writer

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#2196]
#2195 adds a new version of the `carrierDefinition` including new versions of Reader/Writer.

For those, the tests are still missing and must be added.

**Comment by kt86** [comment]
@nixlaos Can you please check, if this is already done? If not, could you please do it?

**Comment by nixlaos** [comment]
ReadWriteTest was set up in PR#2464 covering new fields including jsprit score attribute
