### ISSUE TITLE
Empty sets not loaded correctly from ConfigGroup

### ISSUE THREAD

**Issue by marecabo** [matsim-org/matsim-libs#2225]
Thanks for the parameter annotation also for sets/lists in ConfigGroups by @michalmac in #2202!

I noticed, when saving and loading config groups with empty sets, that they are not loaded the same again.

Say we have a config group with

```java
    @Parameter
    @NotNull
    public Set<String> licenseModes = Set.of(TransportMode.car);

    @Parameter
    @NotNull
    public Set<String> drtModes = Collections.emptySet();
```

and save and load that config group, the resulting values will be:

```java
System.out.println(configGroup.licenseModes); // {"car"}
System.out.println(configGroup.drtModes); // {""} <-- set with empty string as element, not an empty set
```

Should it be like it is currently or should an empty set also be loaded as an empty set? Intuitively, I would prefer the latter.

**Comment by michalmac** [comment]
I agree, we should return `{}` rather than `{""}`. I will fix it.

**Comment by marecabo** [comment]
Thanks! Fortunately, there is only one test which fails when changing to the desired behavior: https://github.com/matsim-org/matsim-libs/actions/runs/3226559716/jobs/5280224784#step:6:997

**Comment by marecabo** [comment]
Thanks for the quick fix. This makes creating config groups a lot more convenient!
