### ISSUE TITLE
Fixed landmark count for SpeedyALT

### ISSUE THREAD

**Issue by severindiepolder** [matsim-org/matsim-libs#2297]
Dear all,
I came across the requirement for a fixed amout of 16 landmarks for the SpeedyALT router when running a very small test network. At that point, I got fatal errors because my network was too small, so not enough landmarks could be assigned. I only found out about the relation between the fixed amount of landmarks and the network with a too-small amount of nodes after digging into the code and finding out how the landmarks are assigned. 

The landmark creation takes place in org.matsim.core.router.speedy.SpeedyALTFactory.createPathCalculator()

Later I found a mention of the 16 landmarks in org.matsim.core.router.speedy.SpeedyALT. The values also correspond to the recommendation of 16 landmarks as a good trade-off for computational time and the efficiency of the algorithm in the literature. (Computing the Shortest Path: A* Search Meets Graph Theory" by Andrew V. Goldberg and Chris Harrelson, 2005)

Would you agree that some changes to avoid fatal errors in small networks or a precise error that states that at least 16 nodes are needed would be helpful?

Best regards
Severin

**Comment by paulheinr** [comment]
That should be fixed with #2559.
