### ISSUE TITLE
ev: fail if battery SOC outside [0, 1] is problematic

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#2315]
I'm currently experiencing problems that are related to #2301 and the changed interface of Battery . It feels like, I am the first person testing this PR on large (non-test scenarios). In my opinion it can and will happen (only a matter of time) that an EV has underestimated his travel time, get stuck in traffic jam and runs thus out of juice. With #2301 the simulation throws now a pretty nice exception. As one could see in this PR you were forced to increase the battery capacity from 60 to 65 kwh to ensure valid test results. However it might be that if you simulate 20 more iterations even 65 kwh is not enough in a spacial corner case. Could we please rethink and mitigate this PR? Here are some options:

1.	Throw error log messages for vehicles that would run with SOC < 0
2.	Make BatteryImpl exchangeable with different behaviors 
3.	Let the user decide whether the simulation throws and error or an error log msg (config switch)

**Comment by michalmac** [comment]
Thanks @steffenaxer for your feedback. We are aware of the issue and have been discussing many solutions (even like letting the battery SOC go below 0). The one we like most is keeping the SOC lower-bounded at 0 and emit a `MissingEnergyEvent` whenever we would run below 0. This way we can easily gather info on when we lacked some energy (time, location, vehicle, amount of energy). That info can be used for the next iterations (e.g. adding more charges, switching to non-EVs).

BTW. It's also possible to run out of the battery in regular (i.e. non-DVRP) replanning. Not sure if we want to accept this or not (in this case it's not about the inaccuracy of predictions, IMO it's a flaw or bug in the planning logic, I haven't yet looked into it). The current implementation uses the components from the EV simulation (battery, energy consumption models), however in this case we should not throw events, so we need to address this too.

**Comment by steffenaxer** [comment]
Dear @michalmac, thanks for your prompt answer. Yes, I like the approach with lower-bounded SOC and the MissingEnergyEvent. It gives MATSim the Feedback and users can react to this event with various strategies. I think even in dvrp (drt) or non-dvrp there might be always a difference between planned travel time and executed. Thus the main cause is imho always the same. 

In DRT one could react with a more sophisticated charging strategy to this problem. E.g. always ensure that vehicle is able to reach a charger. Because till now, the drt accepts request till its SOC is lower than 20 %. However, it may be that the remaining charge is enough to serve this request but not enough to reach the safe harbor 😊 

In non-DRT situations the replanning needs to come around with MissingEnergyEvent an plan more energy reliable plans. I’m not aware of this, because I haven’t used non-Drt EVs, and I even do now know whether there is a really sophisticated charging replanning strategy. I know that @tschlenther had here some contributions, but imho this code has not reached perfection and might also require assumptions of behavioral decision making. Anyway, non-drt EVs are and important thing!

I would call for a fast first aid solution and vote for the lower-bounded SOC and the MissingEnergyEvent.

**Comment by michalmac** [comment]
#2316 adds support for `MissingEnergyEvent`. These events are created during simulation when we run out of battery.

We still get exceptions in the replanning phase (`UrbanEVTripsPlanner`). This requires some more investigation.

**Comment by tschlenther** [comment]
The UrbanEVTripsPlanner emulates the charging in order to estimate the consumption and uses the EV infrastructure (e.g. an instance of `ElectricVehicle` etc) for that. I did not have a look yet, this might be the reason why we still experience exceptions there. Maybe @rgraebe can help digging into that in the next days?

**Comment by tschlenther** [comment]
Ah sorry I misunderstood you comment @michalmac.
I'll have to look closer, but probably we'll want to change from the exception to something like a warning, only. This is because we are just emulating/planning in `UrbanEVTripsPlanner` and after `emulateVehicleDischarging` (where the exception is currently thrown), we check for the SoC to be below a certain percentage or not, anyways.

**Comment by michalmac** [comment]
> I'll have to look closer, but probably we'll want to change from the exception to something like a warning, only. This is because we are just emulating/planning in UrbanEVTripsPlanner and after emulateVehicleDischarging (where the exception is currently thrown), we check for the SoC to be below a certain percentage or not, anyways.

Thanks. It makes sense. Then you need to remove this line (ignoring) or replace with some warning log (but this could produce lots of warning even for a single leg):
https://github.com/matsim-org/matsim-libs/blob/master/contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVTripsPlanner.java#L662
