### ISSUE TITLE
MatsimTestUtils.compareEventsFiles(...) calls deprecated comparing method

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#2327]
https://github.com/matsim-org/matsim-libs/blob/bc5b9f001d020d4b82804adbdd82db7ea8fdf759/matsim/src/test/java/org/matsim/testcases/MatsimTestUtils.java#L360-L362

calls a deprecated comparison method: 

https://github.com/matsim-org/matsim-libs/blob/bc5b9f001d020d4b82804adbdd82db7ea8fdf759/matsim/src/main/java/org/matsim/utils/eventsfilecomparison/EventsFileComparator.java#L73-L97

The correct one is - avoiding the transformation of the `Result` to an `int:`
https://github.com/matsim-org/matsim-libs/blob/bc5b9f001d020d4b82804adbdd82db7ea8fdf759/matsim/src/main/java/org/matsim/utils/eventsfilecomparison/EventsFileComparator.java#L128-L130

Should we just change it, accepting, that this will maybe break code / let tests behave differently, because the return value of this method changes...?

Or should we add (another) method to `MATSimTestUtils`?

**Comment by michalmac** [comment]
I think we should gradually remove deprecated methods to avoid accumulating code endlessly. Even Java is from time to time cleaned up from some deprecated functionality. Of course, removing must be done in a way that the matsim-lib compiles.

Moreover, these files are in the test scope and we should not try to promise any backward compatibility for non-production code.

**Comment by michalmac** [comment]
I just noticed that `EventsFileComparator` is a prod class. Anyway I still vote for removal of the deprecated methods.
