### ISSUE TITLE
Sub Scenario Cutting / Extraction

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-libs#2437]
We are interested in extracting realistic subsets from larger MATSim models. For example, a city out of a regional model. 

We wish to maintain reasonable external demand for around this subset.

Before developing this we wish to review what capability already exists (we are sure we're not the first to want this!). 

I can see some old (2015) code [here](https://github.com/matsim-org/matsim-libs/commit/3c88191557eba19df3404bd61a9005602cdee3a1) and references to the Zurich subset code [here](https://github.com/matsim-eth/baseline_scenario).

We wish to build upon something existing (and contribute back). Any pointers very welcome

**Comment by sebhoerl** [comment]
Hi Gerry,

we have a detailed cutter in eqasim that we can extend (and also move here, potentially):
https://github.com/eqasim-org/eqasim-java/tree/develop/core/src/main/java/org/eqasim/core/scenario/cutter

It cuts everything in detail, for instance vehicular routes such that vehicles enter the area at the exact point of entry along the cutting border. PT lines etc. are also cut. We work with "outside" activities that are created on the border whenever agents enter or exit the cut area and "outside" legs that connect the activities if agents exit the study area at some point and enter again later on.

There is a detailed description in chapter 4.2 here:
https://www.research-collection.ethz.ch/handle/20.500.11850/419837

**Comment by gac55** [comment]
Excellent @sebhoerl - thank you!
