### ISSUE TITLE
Adding attribute for each activity in initial demand population file 

### ISSUE THREAD

**Issue by gharaviSara** [matsim-org/matsim-libs#2596]
Dear all
I’m trying to use eqasim for specific spatial attribute mode choices models which need the density and diversity calculated for each location of activity 
I’m using Swiss based python pipeline to generate my population 
But in the population file when I defined my python based matsim. Writer
With this example structure 
I received this error 

 
 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "[http://www.matsim.org/files/dtd/population_v6.dtd">](http://www.matsim.org/files/dtd/population_v6.dtd%2522%3E)
<population desc="Switzerland Baseline">
  <person id="8246">
    <attributes>
      <attribute name="person_id" class="java.lang.Long">8246</attribute>
      <attribute name="age" class="java.lang.Integer">4</attribute>
      <attribute name="hasLicense" class="java.lang.String">yes</attribute>
      <attribute name="sex" class="java.lang.Integer">1</attribute>
      <attribute name="isCarPassenger" class="java.lang.Boolean">false</attribute>
      <attribute name="household_id" class="java.lang.Long">3404</attribute>
      <attribute name="hts_person_id" class="java.lang.Long">60041</attribute>
      <attribute name="householdIncome" class="java.lang.Double">1</attribute>
      <attribute name="pt_non_subscription" class="java.lang.Double">1.0</attribute>
    </attributes>
    <plan selected="yes">
      <activity type="home" x="265005.000000" y="5198595.000000" facility="home3404" end_time="10:00" />
      <attributes>
        <attribute name="density_o" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_o" class="java.lang.Double">0.5</attribute>
        <attribute name="density_d" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_d" class="java.lang.Double">0.5</attribute>
      </attributes>
      <leg mode="car" dep_time="10:00" trav_time="00:32" />
      <activity type="education" x="255135.000000" y="5186698.000000" facility="218487" start_time="10:32" end_time="12:00" />
      <attributes>
        <attribute name="density_o" class="java.lang.Double">1.54</attribute>
        <attribute name="hhi_o" class="java.lang.Double">0.75</attribute>
        <attribute name="density_d" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_d" class="java.lang.Double">0.5</attribute>
      </attributes>
      <leg mode="car" dep_time="12:00" trav_time="00:32" />
      <activity type="home" x="265005.000000" y="5198595.000000" facility="home3404" start_time="12:32" end_time="14:00" />
      <attributes>
        <attribute name="density_o" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_o" class="java.lang.Double">0.5</attribute>
        <attribute name="density_d" class="java.lang.Double">1.54</attribute>
        <attribute name="hhi_d" class="java.lang.Double">0.75</attribute>
      </attributes>
      <leg mode="car" dep_time="14:00" trav_time="00:32" />
      <activity type="education" x="255135.000000" y="5186698.000000" facility="629408" start_time="14:32" end_time="17:00" />
      <attributes>
        <attribute name="density_o" class="java.lang.Double">1.54</attribute>
        <attribute name="hhi_o" class="java.lang.Double">0.75</attribute>
        <attribute name="density_d" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_d" class="java.lang.Double">0.5</attribute>
      </attributes>
      <leg mode="car" dep_time="17:00" trav_time="00:32" />
      <activity type="home" x="265005.000000" y="5198595.000000" facility="home3404" start_time="17:32" end_time="19:00" />
      <attributes>
        <attribute name="density_o" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_o" class="java.lang.Double">0.5</attribute>
        <attribute name="density_d" class="java.lang.Double">1.54</attribute>
        <attribute name="hhi_d" class="java.lang.Double">0.75</attribute>
      </attributes>
      <leg mode="car" dep_time="19:00" trav_time="00:14" />
      <activity type="leisure" x="250879.000000" y="5191894.000000" facility="178852" start_time="19:14" end_time="20:30" />
      <attributes>
        <attribute name="density_o" class="java.lang.Double">0.25</attribute>
        <attribute name="hhi_o" class="java.lang.Double">0.86</attribute>
        <attribute name="density_d" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_d" class="java.lang.Double">0.5</attribute>
      </attributes>
      <leg mode="car" dep_time="20:30" trav_time="00:14" />
      <activity type="home" x="265005.000000" y="5198595.000000" facility="home3404" start_time="20:44" />
      <attributes>
        <attribute name="density_o" class="java.lang.Double">0.03</attribute>
        <attribute name="hhi_o" class="java.lang.Double">0.5</attribute>
        <attribute name="density_d" class="java.lang.Double">0.25</attribute>
        <attribute name="hhi_d" class="java.lang.Double">0.86</attribute>
      </attributes>
    </plan>
  </person>
 
 
but raise  error 
org.xml.sax.SAXParseException; lineNumber: 72; columnNumber: 12; The content of element type "plan" must match "(attributes?,(activity|leg)*)".
 
 
 
 
https://github.com/matsim-org/matsim-code-examples/issues/671

**Comment by gharaviSara** [comment]
_
![Uploading F4CF2003-9EBE-4D2D-B758-759FC953CB08.png…]()
_

**Comment by mrieser** [comment]
please ask eqasim-related questions in the eqasim-repository: https://github.com/eqasim-org
