### ISSUE TITLE
Any link to download this version of MATSIM org.matsim:matsim:jar:12.0-2020w15-SNAPSHOT?

### ISSUE THREAD

**Issue by sakibk005** [matsim-org/matsim-libs#2597]
Hello, I am trying to build the matsim_los-angeles model but it fails as the underlying version of matsim is not available now. I wanted to see if anyone could assist me to retrieve this specific version 'org.matsim:matsim:jar:12.0-2020w15-SNAPSHOT'. Thank you in advance.

**Comment by mrieser** [comment]
`2020w15` describes week 15 of 2020, that is the week starting April 12, 2020.

You could try to use version `12.0` which was released in early June 2020. Hopefully the changes between April and June were not that big, such that your model still works.
