### ISSUE TITLE
Auto-merge does not wait for open reviews

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#2652]
The auto-merge merges a PR automatically, even if there are open reviews. 
I think, that it should **not** behave like that and rather wait for the reviewer's go.

One can discuss, whether it needs a go from all reviewers or if just one go is enough. 
But merging directly after all GH actions tests have passed, is at least for me a bit over-motivated.

@michalmac : I have not looked into the configuration yet. But as far as I know, GH supports some kind of blocking until reviewers gave their go. Do you (or someone else) know the setting by heart? Otherwise, I would look it up next week.

**Comment by kt86** [comment]
See e.g. #2651 which was merged, before I was able to review.

**Comment by michalmac** [comment]
The simplest rule is: if you want the code to get reviewed, you should not enable auto-merge. Even if the review is positive, it may point out some minor issues that you may want to consider before merging.

Yes, there is an option to block merging until the PR gets approved. However, if we enable it, all PRs would need to get a positive review. That's a big commitment though.

**Comment by kt86** [comment]
Yes, I know that simple rule. :) I think that we have already discussed it somewhere, earlier... (but did not found it in the issues)

Argh, I forgot about that issue, that one than needs at least a positive review.... 
(Most probably will someone out there write a bot, one can ask for the review, and it will automatically give you the "go" ^^)

So, I am convinced, that we leave it as it is and will close this here.
