### ISSUE TITLE
race condition (?) in ParallelPopulationWriterHandlerV6

### ISSUE THREAD

**Issue by Royal2Flush** [matsim-org/matsim-libs#2692]
As already mentioned in my last issue concerning the new Parallel IO, there is something not quite right with the new Writer too. While until now I have not been able to come up with a minimal example that reliably reproduces the error, I can at least point to where things are going wrong:

We have a test that reads through a population with a streaming reader, funnels each person through a PersonAlgorithm that splits some persons into multiple new persons that each have parts of the original person's plan, and then writes out the new persons with a streaming writer.

Currently this test fails because some elements in the new plans are wrong or missing (e.g. activity start times seem to be wrong or missing quite often, while activity end times always have been correct so far). This happens in about 90% of the test runs.

The issue is **fixed** by adding `TimeUnit.SECONDS.sleep(1);` after line 187 of `ParallelPopulationWriterHandlerV6` (between `this.inputQueue.put(new PersonData(person, f));` and `this.outputQueue.put(f);`). So far in any runs with the artificial delay the test passed and as soon as I take the delay out it fails again. It seems like some thread is processing either the `PersonData` or the generated String before it is ready.

Edit: Putting the sleep one line further up (before `this.inputQueue.put(new PersonData(person, f));`) does not fix the problem, so I am quite confident the issue is within the WriterHandler).

I will investigate this further and try to come up with a more precise problem description, but maybe @steffenaxer has an idea what could be the issue here?

**Comment by mrieser** [comment]
I just performed the following test:

- convert Santiago/v1/input/plans_final.xml.gz from v5 to population_v6.dtd.
- Read in network and plans(v6) into a scenario --> Reference-Scenario
- in a loop, read in network and plans(v6) into a new scenario --> Test-Scenario
  - compare for each person, each activity the activity-starting-time between the Reference-Scenario and the Test-Scenario

I repeated the loop 50 times, not a single error was reported, although the parallel population reader for v6 was used.

I also used the StreamingPopulationReader to read in the population in the test-scenario, comparing the activities immediately as they were passed to the PersonAlgorithm. Again, no comparison-errors were reported.

So it seems for at least basic use cases the regular PopulationReader and StreamingPopulationReader behave correct --- which does not yet rule out there might be some more complex case where something goes wrong. So please provide a test-case that reproduces the problem, otherwise we don't know where to search further from here.

**Comment by steffenaxer** [comment]
Independenlty to Marcel I implemented a test class. See [link](https://github.com/matsim-org/matsim-libs/compare/master...steffenaxer:matsim-libs:senozonTest)

The class reads a population with new parallel stream reader, makes a person and plan copy from the selected plan.
Person and plan is compred on object scope after creating the copies.
Content is dumped with new parallel stream writer, loaded again and than gets compared a second time.

This class runs fine even for very large output plans (e.g. hamburg or berlin scenario)

**Comment by steffenaxer** [comment]
Update: [link](https://github.com/matsim-org/matsim-libs/compare/master...steffenaxer:matsim-libs:senozonTest) tests now start and end times, everyhing looks good in this test.

**Comment by mrieser** [comment]
@Royal2Flush as you seem to have a case that creates the problem, can you please share some code? Just from the description, we cannot reproduce the problem.

**Comment by Royal2Flush** [comment]
The tested class has quite a few dependencies to our proprietary codebase. I'm currently trying to create a more minimal example, which I hope I get done by tomorrow as I'll be on vacation for a month afterwards.

**Comment by Royal2Flush** [comment]
I found the issue. Due to the String creation being offloaded to a separate thread, modifications to the person that are made after the write() instruction may affect the output String and even lead to inconsistent plans where the first part is in the state as it was when the writer received it and another part in a modified state.

Take the following testclass with the example population:
```
package org.matsim.core.population.io;

import org.matsim.api.core.v01.Coord;
import org.matsim.api.core.v01.population.Activity;
import org.matsim.api.core.v01.population.Person;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.population.algorithms.AbstractPersonAlgorithm;
import org.matsim.core.router.TripStructureUtils;
import org.matsim.core.router.TripStructureUtils.StageActivityHandling;
import org.matsim.core.scenario.ScenarioUtils;

public class Testclass {

	public static void main(String[] args) {
		String workingdir = "W:/tmp/parallelTest/";//args[0];
		Handler handler = new Handler(workingdir);
		StreamingPopulationReader reader = new StreamingPopulationReader(ScenarioUtils.createScenario(ConfigUtils.createConfig()));
		reader.addAlgorithm(handler);
		reader.readFile(workingdir + "inputPop.xml");
		handler.finish();
	}

	private static class Handler extends AbstractPersonAlgorithm {
		private final StreamingPopulationWriter writer;
		
		Handler(String outdir) {
			this.writer = new StreamingPopulationWriter();
			this.writer.startStreaming(outdir + "out.xml");
		}

		@Override
		public void run(Person person) {
			writer.writePerson(person);
			for (Activity act : TripStructureUtils.getActivities(person.getSelectedPlan(), StageActivityHandling.ExcludeStageActivities)) {
				act.setStartTimeUndefined();
				act.setEndTimeUndefined();
				act.setCoord(new Coord(0, 0));
			}
		}
		
		public void finish() {
			writer.closeStreaming();
		}
	}

}
```
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v6.dtd">
<population desc="population written from streaming">
	<person id="testperson">
		<plan selected="yes">
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" end_time="00:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="01:00:00" end_time="02:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="03:00:00" end_time="04:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="05:00:00" end_time="06:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="07:00:00" end_time="08:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="09:00:00" end_time="10:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="11:00:00" end_time="12:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="13:00:00" end_time="14:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="15:00:00" end_time="16:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="17:00:00" end_time="18:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="19:00:00" end_time="20:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="21:00:00" end_time="22:00:00" />
			<leg mode="walk" trav_time="01:00:00"/>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="23:00:00" />
		</plan>
	</person>
</population>
```
On my computer this leads to the following output file:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v6.dtd">

<population desc="population written from streaming">



<!-- ====================================================================== -->

	<person id="testperson">
		<plan selected="yes">
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" end_time="00:00:00" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
		</plan>

	</person>

<!-- ====================================================================== -->

</population>
```
As you can see the first Activity is unmodified, whereas all subsequent acts are in the modified state.

If I add an artificial delay of 500ns after the line `writer.writePerson(person);` or after the above mentioned line 187 of `ParallelPopulationWriterHandlerV6`, approximately the first half of the activities are in their original state:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v6.dtd">

<population desc="population written from streaming">



<!-- ====================================================================== -->

	<person id="testperson">
		<plan selected="yes">
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" end_time="00:00:00" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="01:00:00" end_time="02:00:00" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="03:00:00" end_time="04:00:00" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="05:00:00" end_time="06:00:00" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="782358.0" y="5943609.0" start_time="07:00:00" end_time="08:00:00" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="782493.0" y="5943860.0" start_time="09:00:00" end_time="10:00:00" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="work" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
			<leg mode="walk" trav_time="01:00:00">
			</leg>
			<activity type="home" link="" facility="123456" x="0.0" y="0.0" >
			</activity>
		</plan>

	</person>

<!-- ====================================================================== -->

</population>
```
With a delay of 2ms consistently all activities are written in their original state.

In my eyes this is not expected behavior of a `write()` function. The Person should be written in the state it was received by the writer and not be affected by any later modifications.

Since the whole point of the parallel writer was to outsource the String creation to a separate thread, maybe it is an option to create a deep copy of the received person and passing that to the string creator? That way later modifications to the original Person will not affect the output file.

**Comment by kainagel** [comment]
I think what @mrieser writes makes sense.  Java has a certain data model, which implies passing around references of possibly mutable objects, and we have to accept it as long as we stay with the language and want to have fairly fast code.

I could imagine a `ConcurrentModificationException` which fails if the object is modified while it is written.  Can't say how difficult this is to implement, and how much performance it would cost.

**Comment by Royal2Flush** [comment]
In principle I'm not opposed to having the writer write the object's state to an arbitrary time later, but this behavior should be made very clear. I do think that the default expectation to a `write()` method is that whatever is passed gets written. The current behavior I would more expect from something called `addToWriteQueue()` or similar where it is clear that it's not written as direct part of the method. The state right now can easily lead to very hard to find bugs. The exception idea by @kainagel could be an option for this.

At the very least I would add a new constructor to `StreamingPopulationWriter` with a boolean that allows me to get the old `PopulationWriterHandlerImplV6` for a writer that ensures the old behavior plus a fat warning in the Writer's javadoc.

**Comment by mrieser** [comment]
A `ConcurrentModificationException` would require that the Person tracks all its changes. ALL its changes, even those within an activity within a plan. The current API does not really allow that.

We plan to introduce a System Property which disables parallel IO for backward compatibility, something like `matsim.parallelIO=false`, similar to the existing flag `matsim.preferLocalDtds=true`. This property will affect the use of the parallel population reader and writer, the use of the parallel events reader, and potential future similar optimizations.

**Comment by Royal2Flush** [comment]
Is there a strong argument against allowing explicit and punctual access to the non-parallel writers? I could imagine scenarios where one would like to write out some but not all files with the parallel writers. Currently this is not possible as far as I can see because the writers themselves are package-private and the generic `StreamingPopulationWriter` does not allow for such selection.

**Comment by kainagel** [comment]
For the mobsim, at some point we said that we would no longer support the non-threaded variant to reduce maintenance burden.

**Comment by mrieser** [comment]
https://github.com/matsim-org/matsim-libs/pull/2700 introduces a System property `matsim.useParallelIO`, which disables parallel readers and writers when set to false (`java -Dmatsim.useParallelIO=false ..... `).

> Is there a strong argument against allowing explicit and punctual access to the non-parallel writers?

As mentioned from Kai, maintenance cost. Not only in the code, but also in documentation and user guidance. We strive to keep the number of options and config parameters as low as possible in order to prevent confusion and misconfiguration. But with MATSim being an open source project, feel free to create a Pull Request with a more fine granular way to control the desired features.
