### ISSUE TITLE
output_trips.csv in MATSim 15 has empty main_mode

### ISSUE THREAD

**Issue by mrieser** [matsim-org/matsim-libs#2779]
In various models run with MATSim 15 I observed that the main_mode column in `output_trips.csv` is empty.
Should be fixed ;-)

**Comment by rakow** [comment]
I think this might already be fixed in #2680

**Comment by mrieser** [comment]
Thanks for the link to the issue. I will have a look at it, and probably use the time then to write a test case so the main_mode won't be empty again in the future.
