### ISSUE TITLE
More flexible counts format

### ISSUE THREAD

**Issue by rakow** [matsim-org/matsim-libs#2780]
The current counts format is very limited, as it can only store volumes for one mode at a fixed hour interval.

@hzoerner was working on a new format that allows for different mode-specific observations with flexible interval. `counts-v2` contains the current implementation, there are a few tasks left:

- Consolidate the xml schema and create a xsd file
- Backward compatibility and possible replacement of the old Counts class. Currently, everything is separated.

**Comment by mrieser** [comment]
Haven't had a look yet at counts_v2, but that sounds very welcome! 👍 

Hopefully it no longer starts counting at 1 but at 0, if at all :-)
