### ISSUE TITLE
Store vehicle type in PersonVehicles

### ISSUE THREAD

**Issue by rakow** [matsim-org/matsim-libs#2801]
Currently, it is presumably not possible to have agents with differentiated vehicle types in `PersonVehicles` when using mode vehicles.

This feature would be useful when working with populations that may use a variety of types. E.g freight agents with different types of trucks. The differentiation is especially important when working with count data, since trucks and smaller cars are often counted separately.

**Comment by mrieser** [comment]
Oh, I just learned about PersonVehicles! Nice, good to know. In the past I had to teach people complex workarounds to assign specific vehicles to agents in the demand modeling process, as the Map could not be easily (de)serialized in the agent attributes. Looks like this should be easier now. I might talk to you next week to learn more about this.

**Comment by marecabo** [comment]
Maybe, we can discuss this [issue](https://github.com/matsim-org/matsim-libs/issues/2689) (sparked from my https://github.com/matsim-org/matsim-libs/pull/2669#issuecomment-1617585066) and the general approach on it in this context next week. There is a rather "aggressive" getter which raises an exception if PersonVehicles are not set:

https://github.com/matsim-org/matsim-libs/blob/224877a3160efeb6ecbb989e862b507834da4af7/matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java#L132-L148
