### ISSUE TITLE
Output evolution of memory usage during execution

### ISSUE THREAD

**Issue by tkchouaki** [matsim-org/matsim-libs#2803]
To be labelled with Performance and Code Sprint

Currently the Memory observer writes the memory usage regularly in the log. 
To better assess this aspect, I think it would be good to have this output in a separate file that can be processed easily and combined with the stopwatch file to see which parts of the process require more memory. 
There are two ways to do this:

- Natively in MATSim by editing the memory observer, can be quite invasive because the MemoryObserver doesn't depend on other components right now and implementing this feature would require to provide the OutputDirectory at least and optionally the StopWatch

- Writing a script that processes the logs and finds the lines written by the memory observer and writes out a specific csv

The potential solutions will be discussed to determine the most appropriate one for implementation.

**Comment by rakow** [comment]
I think something similar to the second proposal is already implemented in `contribs/application/src/main/java/org/matsim/application/analysis/LogFileAnalysis.java`

**Comment by tkchouaki** [comment]
I didn't know about this, it serves the purpose I described. Thank you.
