### ISSUE TITLE
Explicitly allow group requests for DRT

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/matsim-libs#2806]
So far there is no option to have multiple agents requesting a group trip in DRT. In reality we observe that quite a high share of requests are actually group bookings.

While in most cases the standard drt optimizer is able to assign the same vehicle for multiple indiviual requests with same cahracteristics, it can lead to artifacts especially in high-demand scenarios with higher groups and smaller vehicle capacities (i.e., one request is accepted, the other rejected or assigned to a different vehicle).

One could probably collect multiple passenger ids per request and adjust the seat capacity checks in the insertion.

**Comment by nkuehnel** [comment]
Essentially it's going to be closer to what you did in Alonso-Mora for MATSim - at least so far :) 

So the RequestInserter will decide which requests belong together and schedule them together. The actual decision will likely be an interface such as "GroupBookingIdentifier" which can then be implemented differently. Our current historical data usually tags the matsim person with a group attribute (since in our fleet simulations every request is its own agent). This person attribute will then be used in my first implementation.

I agree that this would be even better to have it at the request level. (I'm still not 100% sure if it would indeed be better to have DrtRequests that allow for multiple passenger references in the end)...

**Comment by nkuehnel** [comment]
.. in the latter case one would probably need to solve the joint departure/request submission again

**Comment by michalmac** [comment]
- I would keep this info in DrtRequest.
- We can make DrtRequest an interface for more flexibility.

> Changing code at the request level seems to be too complicated for this feature, as it would have implications all the way up to the QSim, agent departure handling and pickup/dropoff activity handling.

Maybe let's together have a look at the corresponding code to assess the impact of such changes?

**Comment by nkuehnel** [comment]
@michalmac 
Sounds good to me, the interface might also allow more complex use cases later (i.e., different seating requirements / wheelchair customers, etc.)
Happy to look at the code together, maybe you have some time these days during the sprint?

**Comment by michalmac** [comment]
> Happy to look at the code together, maybe you have some time these days during the sprint?

@nkuehnel Sure, just sent you an email.
