### ISSUE TITLE
Get rid of Fast*-routing algorithms

### ISSUE THREAD

**Issue by mrieser** [matsim-org/matsim-libs#2816]
MATSim currently has a long list of (network) routing algorithms:

- Dijkstra
- AStarEuclidean
- AStarLandmarks
- FastDijkstra
- FastAStarEuclidean
- FastAStarLandmarks
- SpeedyALT

The Fast*-variants where introduced by @cdobler several years ago, providing higher performance at the cost of slightly more memory usage.

Since the introduction of SpeedyALT they no longer provide any real benefit, as SpeedyALT is faster and uses less memory than the Fast*-implementations.

In addition, the Fast*-Implementations use a special network representation (`RoutingNetwork`, `ArrayRoutingNetwork`) and also need special handling in `TravelTimeCalculator`, making code more complex.

I would thus suggest to remove the Fast*-implementations and related classes to make the code more lean and simple.

To maintain backwards-compatibility of config-files, the infrastructure from #2473 (related issue #1276) could be used to map any Fast*-entry in the config to SpeedyALT.

**Comment by kainagel** [comment]
+1

We might need to keep Dijkstra around since there are other algos (the old transit router; the accessibility stuff) which (maybe) depends on it.

Or we clean up there as well.

**Comment by mrieser** [comment]
I plan to only remove the Fast* variants. regular Dijkstra and AStarLandmarks should be kept, also as "teaching example"

**Comment by mrieser** [comment]
Closed by #2824
