### ISSUE TITLE
Change default network routing algorithm to SpeedyALT

### ISSUE THREAD

**Issue by mrieser** [matsim-org/matsim-libs#2817]
Currently, the default network routing algorithm is `AStarLandmarks`.

I propose to change the default to `SpeedyALT`, which is considerably faster and has proven to be reliable in the last 2 years.

**Comment by kainagel** [comment]
+1

**Comment by neuma** [comment]
Hi @mrieser, one of our regression tests showed non-deterministic behavior - very same setup, code, input data results in different routes. This seems to be the case whenever there is an alternative route with the same (best) travel time. I nailed it down to the sequence of link preprocessing of the SpeedyGraph. Not sure, if there is a better solution than [fixing the sequence of processing.](https://github.com/matsim-org/matsim-libs/commit/4e57a602a46f2261f7afdb56a810164922c25fe5)

**Comment by michalmac** [comment]
IIRC after switching to SpeedyALT some test became flaky, so this may be related to the issue reported by @neuma.

**Comment by neuma** [comment]
Fix had been integrated into master https://github.com/matsim-org/matsim-libs/pull/3638
