### ISSUE TITLE
Rename freight contrib?

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#2821]
Because freight is more than we are doing in this contrib, e.g. logistics operations. 
For simulating logistic operations, a LogisticsServiceProvider (LSP) can use carriers for some carrying goods on the different stages of the logistic chain.

The carriers are the central part of the current freight contrib, so that could be a feasible name(?).

**Comment by kt86** [comment]
@JWJoubert @rewertvsp @tschlenther This will of course break some code... so I would like to hear your opinion as well.
This is nothing urgent, but may be helpful if we once introduce the `logistics `contrib.

**Comment by kt86** [comment]
From a discussion with @rewertvsp came another idea:
We will keep the `freight` contrib. Inside this contrib everything related to the current freight contrib is moved to a package named `carriers`. When later the logistics part is coming, it will go into a package called `logistics`.

This will also help to not further increase the number of contribs (as discussed in the code sprint).

`drt-extensions` is already doing it similarly, if I have seen it correctly...

**Comment by JWJoubert** [comment]
Hi @kt86,  +1 for moving `carriers` into `freight`. We did discuss it earlier, and at that point I recall we decided that separate contribs would be better. If it would make more sense (given that the LSP and related code might move over), then I can also bring the `freightreceiver` contrib into `freight.receiver`. Let me know. 

I am still busy reimplementing some of the other freight receiver code (collaboration), but what is currently there _works_ at least.

**Comment by kainagel** [comment]
I have to say that my intuition would be to leave them separate for the time being.  It is difficult enough to keep the freight contrib maintained (which indeed right now is mostly a carrier contrib), but at least in terms of its functionality it is much less experimental, and so we "only" have to clear up the API (in particular those parts of it that look different from the matsim person API).

**Comment by kainagel** [comment]
After additional discussion with @kt86 
* leave separate repositories for the time being (i.e. freight, logistics, receiver)
* change package naming scheme to `org.matsim.freight.carrier`, `org.matsim.freight.logistics`, `org.matsim.freight.receiver`.  I.e. (1) drop the contrib (which is really in the way every time we move material from contrib to core), (2) move (much of) the current `freight` material into a `carrier` sub-package, and (3) keep open the option to move material into the `freight` contrib by (a) keeping its name and (b) change the package naming scheme as outlined above.

**Comment by JWJoubert** [comment]
I am not 100% sure I am following, @kainagel. It seems that _"leave separate repositories..."_  is contradicting _"drop the contrib..."_. But, granted, I was not part of the conversations.

Go ahead, I will see what the changes are and adapt accordingly.

**Comment by kt86** [comment]
Dear @JWJoubert , 
replace the word `repository` by `contrib` ;) -> meaning that we have (currently 2, soon 3) different contribs (freight/carriers; freightReceiver; freightLogistics).

But, we are renaming the packages inside(!) of each contrib to
`org.matsim.freight.carriers.*` ...
`org.matsim.freight.receiver.*` ... instead of `org.matsim.contrib.freightreceiver`
`org.matsim.freight.logistics.*` ...
--> so there is no longer the word `contrib` in the package name & they all follow the scheme `org.matsim.freight.`. 

Once the decision is there to bring all of this three contribs together, this would change make it very easy to move all the stuff from the (freightReceiver ; freightLogistics) contrib into the freight contrib. The reason for making it eaysier is, that nothing will change to the package structure, and thus it should not break any code then - when maybe/hopefully more people are using it.

I hope that clarifies it a bit.
