### ISSUE TITLE
core: ParalellPopulationReader fails without exception

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/matsim-libs#2929]
I just came across an example where the ParallelPopulationReader processes a population, but inside there are inconsistencies (here, a referenced facility that does not exist). In the example, `PopulationUtils.decideOnCoordForActivity` causes a `RuntimeException` through `Gbl.assertNotNull`. While the error is printed in the console, there is no mechanism that let's the "top level" reader fail at the end of the parallel processing. Probably some custom exception handler is missing on the executing thread. If one doesn't look at the log carefully, the only thing that one notices is that there are agents missing ;) 

![Screenshot from 2023-11-13 13-04-50](https://github.com/matsim-org/matsim-libs/assets/647500/36af96a6-6444-477e-8733-71a1288bd86e)

**Comment by steffenaxer** [comment]
I will have a look on this!

**Comment by sebhoerl** [comment]
> The issue is that the parallel reader does not escalate the exception but just continues?

Yes, well summarized :)

**Comment by mrieser** [comment]
Okay, should be easy to write a test for this and fix it.
