### ISSUE TITLE
Cancel a running drt charging

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#2941]
@michalmac is there a way to cancel a running charging?

**Comment by michalmac** [comment]
That's a really good question! We have never looked into this.

The easiest way to terminate charging earlier is to implement your own `ChargingStrategy`. That charging strategy would need to know the optimiser decisions wrt which vehicle should charge for how long (and potentially at what speed). 

Specifically `isChargingCompleted()` is the method responsible for telling the charging logic if a given vehicle should stop charging.

**Comment by steffenaxer** [comment]
Thanks 🙏 implemented it. Stay tuned. PR incoming 🎉
