### ISSUE TITLE
Migration path between config version

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#2960]
One big puzzle piece I'm missing is a migration path between config group versions. Currently matsim throws an error if there is an unknown parameter. In my eyes it would require a handler that could be overwritten per ConfigGroup that allows to say what should happen with an unknown parameter. If nothing is overwritten  the current error is thrown. What do you think @mrieser, @kainagel?

**Comment by mrieser** [comment]
This should be easy to implement, and could be useful.

`ReflectiveConfigGroup` already has a flag `storeUnknownParameters`. In the method `addParam`, this flag is evaluated and the unknown value either stored or an exception is thrown. One could add a new method `handleUnknownParameter(String paramName, String paramValue)` which is not final, so it can be overwritten. 

The current logic of unknown parameter names could be moved to this method. Extending classes could overwrite the method and e.g. produce custom error messages, migrate the value to a newer one (think of having an old parameter which takes km/h, and a new parameter takes m/s, the method could adapt the value and store it with the new name and produce a warning), or implement whatever logic they want themselves.
