### ISSUE TITLE
Extendable DvrpConfigGroup

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/matsim-libs#2962]
@michalmac on my way to an extenable version of the DvrpConfigGroup I discovered the problem, that there is currenlty no way to reload a specialized version from config file (xml) e.g. DvrpConfigGroupWithExtensions. We will end in an unsupported parameter error. 

For the DrtConfigGroup we can use the construct of `MultiModeDrtConfigGroup(Supplier<DrtConfigGroup> drtConfigSupplier)` and call later `createParameterSet` to use custom suppliers. Do you have an idea, how we could get a DvrpConfigGroup that allows also the later loading from xml without throwing errors?

**Comment by michalmac** [comment]
I think you can create a custom instance the dvrp config (e.g. `MyDvrpConfigGroup`) and pass it to `ConfigUtils.loadConfig()`.

**Comment by steffenaxer** [comment]
Yes thats it, will discuss this with Hannes. Thanks!
