### ISSUE TITLE
FreightAnalysis has issues, if vehicle(Types) are not in the allVehicles container

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#3037]
I would like to stay for the analysis with the "allVehicles" container.

If the CarrierReader is the problem, Then we may need the option to read the carriers file even, if some vehicleTypes are missing. This should not be the default because for the normal simulation and tour planning, we require all vehicle types, but here for the analysis, we do not.

_Originally posted by @kt86 in https://github.com/matsim-org/matsim-libs/issues/3036#issuecomment-1878683069_

Please see #3036 with the original issue from @rewertvsp :
Changes the input vehicleFile for the analysis.

 - the reason is that the allVehicles file only contains the types of the used vehicles

Problem: if we read a carrier which uses not all available vehicles the types of this vehicles are not in the allVehicles file, and it creates this [exception](https://github.com/matsim-org/matsim-libs/blob/95612817ff151219caea5b7e13a5cd721b4f2665/contribs/freight/src/main/java/org/matsim/freight/carriers/CarrierPlanXmlParserV2_1.java#L203-L205)
Solution:
 - using the carriersVehicleTypes file instead

**Comment by rewertvsp** [comment]
solved with #3040
