### ISSUE TITLE
Differently sorted modes in network.xml

### ISSUE THREAD

**Issue by markusstraub** [matsim-org/matsim-libs#3134]
I noticed that while juggling networks (e.g. recreating with pt2matsim) a network that did not change at all still has a different xml representation because the order of transit modes per link is not fixed.

So I end up with diffs like this:
```diff
< <link id="229329" from="1095288715" to="337401315" length="42.46496260420861" freespeed="8.333333333333334" capacity="600.0" permlanes="1.0" oneway="1" modes="bus,car" >
---
> <link id="229329" from="1095288715" to="337401315" length="42.46496260420861" freespeed="8.333333333333334" capacity="600.0" permlanes="1.0" oneway="1" modes="car,bus" >
```

I would love to get rid of this behavior. We could change this in `NetworkWriterHandlerImplV2` but I believe a more efficient way is to change it at the source - in `LinkImpl`: https://github.com/matsim-org/matsim-libs/blob/b78e7c7f1e6762a14e872a4fb942691d368b4771/matsim/src/main/java/org/matsim/core/network/LinkImpl.java#L284C4-L284C73 

Instead of an unsorted `Set.copyOf` I propose to use create a sorted set there, e.g. using `com.google.common.collect.ImmutableSortedSet.copyOf` (or something equivalent)

**Comment by steffenaxer** [comment]
Yes, agree. I know this problem. Sounds like a reasonable solution.
