### ISSUE TITLE
Annealing

### ISSUE THREAD

**Issue by lukknapen** [matsim-org/matsim-libs#3242]
How to use annealing ?
Because we have a giant discontinuity in `modestats.png` (see added file) we want to apply annealing (advised by Ihab).
In `config.xml` we use 
```<module name="replanningAnnealer" >
      <param name="activateAnnealingModule" value="true" />
      <!--
      <param name="endValue" value="0.00011" />
      <param name="annealType" value="geometric" />
      <param name="annealParameter" value="globalInnovationRate" />
      <param name="halfLife" value="0.5" />
      <param name="shapeFactor" value="0.89" />
      -->
   </module>
```
- Note that all but one of the settings are commented out.
- Defining any parameter except `activateAnnealingModule` seems to raise an exception.
- The source code `ReplanningAnnealerConfigGroup.java` seems to specify more parameters.
```
    public enum AnnealOption {linear, geometric, exponential, msa, sigmoid, disabled}

    public enum AnnealParameterOption {
        globalInnovationRate, BrainExpBeta, PathSizeLogitBeta, learningRate
    }

   // ....
    public static class AnnealingVariable extends ReflectiveConfigGroup {

        public static final String GROUP_NAME = "AnnealingVariable";
        private static final String START_VALUE = "startValue";
        private static final String END_VALUE = "endValue";
        private static final String ANNEAL_TYPE = "annealType";
        private static final String DEFAULT_SUBPOP = "defaultSubpopulation";
        private static final String ANNEAL_PARAM = "annealParameter";
        private static final String HALFLIFE = "halfLife";
        private static final String SHAPE_FACTOR = "shapeFactor";
        private String defaultSubpop = null;
        private Double startValue = null;
        private double endValue = 0.0001;
        private double shapeFactor = 0.9;
        private double halfLife = 100.0;
        private AnnealOption annealType = AnnealOption.disabled;
        private AnnealParameterOption annealParameter = AnnealParameterOption.globalInnovationRate;

   // ....
        @Override
        public Map<String, String> getComments() {
            Map<String, String> map = super.getComments();
            map.put(HALFLIFE,
                    "this parameter enters the exponential and sigmoid formulas. May be an iteration or a share, i.e. 0.5 for halfLife at 50% of iterations. Exponential: startValue / exp(it/halfLife)");
            map.put(SHAPE_FACTOR, "sigmoid: 1/(1+e^(shapeFactor*(it - halfLife))); geometric: startValue * shapeFactor^it; msa: startValue / it^shapeFactor");
            map.put(ANNEAL_TYPE, "options: linear, exponential, geometric, msa, sigmoid and disabled (no annealing).");
            map.put(ANNEAL_PARAM,
                    "list of config parameters that shall be annealed. Currently supported: globalInnovationRate, BrainExpBeta, PathSizeLogitBeta, learningRate. Default is globalInnovationRate");
            map.put(DEFAULT_SUBPOP, "subpopulation to have the global innovation rate adjusted. Not applicable when annealing with other parameters.");
            map.put(START_VALUE, "start value for annealing.");
            map.put(END_VALUE, "final annealing value. When the annealing function reaches this value, further results remain constant.");
            return map;
        }
    }
```
but i do not understand why these parameters cannot be used (do not understand the mechanism behind this code)
- We used both `matsim-15` (2023-Apr release) and `matsim-2024.0` ("24.0-RC1 (Spring 2024)") and both behave in a similar way.
- In `logfile.log` only one parameter
![modestats](https://github.com/matsim-org/matsim-libs/assets/959111/6c3f4c36-3d46-4792-9158-024cbc396933)
 for module `replanningAnnealer` is listed.
- At this moment we use annealing using the ''standard'' setting (whatever that may be).

Thanks for your help
luk

**Comment by jfbischoff** [comment]
Hi Luk,
you need to define the parameters per Annealing Variable, i.e., it should look like this:
`
<module name="ReplanningAnnealer" >

		
		<param name="activateAnnealingModule" value="true" />
		<parameterset type="AnnealingVariable" >
			
			<param name="annealParameter" value="globalInnovationRate" />
			
			<param name="annealType" value="sigmoid" />
			
			<param name="defaultSubpopulation" value="regular" />
			
			<param name="endValue" value="0.01" />
			
			<param name="halfLife" value="0.425" />
			
			<param name="shapeFactor" value="0.05" />
			
			<param name="startValue" value="0.65" />
		</parameterset>
	</module>
`

With the settings above, the stopwatch for a typical run in our setup looks like that:
One can clearly see that there is more replanning initially, which is gradually being reduced.

![grafik](https://github.com/matsim-org/matsim-libs/assets/9839518/003c98cf-a733-4ab5-9117-d0e6253e4883)


Note that multiple subpopulations are only supported in the 2024 RC, before that defining the same Annealing Variables for multiple subpopulations led to an error.

**Comment by lukknapen** [comment]
- thanks a lot Joschka
