### ISSUE TITLE
Regression test reference files generated with Mac M3 / ARM may cause trouble

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/matsim-libs#3244]
I had some trouble updating test reference files that were generated on my Mac with M3 chip when working on this PR (tests ran through locally but not on github):
https://github.com/matsim-org/matsim-libs/pull/3224

A problem might be that the population equals method relies on raw bytes of gzipped files:
https://github.com/matsim-org/matsim-libs/blob/d5db30ac794381d64ef2ed168f0fb2edb0310404/matsim/src/main/java/org/matsim/core/population/PopulationUtils.java#L659-L677

Changing to the population comparison class
https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/core/population/routes/PopulationComparison.java

and updating it to include pairwise plan elements comparison in 
[564cf47](https://github.com/matsim-org/matsim-libs/pull/3224/commits/564cf47cdec69482b1bd442fbe353edfc2e14d0a)

worked. 

In lack of a better explanation so far I'm leaving this issue as a FYI in case someone runs into the same issue.

If the diagnosis is correct, we might even think of removing the by-byte comparison of populations (which isn't that helpful in terms of identifying what is different anyways.. the events file comparator is much more helpful in that regard)

**Comment by michalmac** [comment]
I remember @luchengqi7 ran into the same issue several times. This was related to comparing scores. The problem is that the FP works sometimes (*) a bit different on mac and intel CPUs.

(*) AFAIR this difference is not coming from simple FP arithmetic operators. It's more related to more complex calculations, e.g. calling the `exp()` function (which I think we do in scoring).

**Comment by michalmac** [comment]
I think asserting the equality of plan scores with some (even very small) delta should be enough.

**Comment by michalmac** [comment]
> (*) AFAIR this difference is not coming from simple FP arithmetic operators. It's more related to more complex calculations, e.g. calling the exp() function (which I think we do in scoring).

This could depend on the specific JDK distribution and the math libs it uses. But I am not expert at all here.

**Comment by nkuehnel** [comment]
I tried to replace the comparison in other tests as well
https://github.com/matsim-org/matsim-libs/pull/3247/
