### ISSUE TITLE
Delete ExperimentalTransitRoute if possible

### ISSUE THREAD

**Issue by paulheinr** [matsim-org/matsim-libs#3349]
Since it is marked as deprecated and pollutes code, it should be deleted if possible
`org.matsim.pt.routes.ExperimentalTransitRoute`

It is replaced in `PersonPrepareForSim` with a `DefaultTransitPassengerRoute`

**Comment by paulheinr** [comment]
It is deprecated since 2020. So I would say, it's totally fine that the phase of backward compatibility is over.

**Comment by vsp-gleich** [comment]
To me it seems all occurences of ` org.matsim.pt.routes.ExperimentalTransitRoute` are needed to read in an old plans file with `ExperimentalTransitRoute` and have it converted to  `DefaultTransitPassengerRoute`. That means we can either remove that backward compatibilty or there is nothing to be done.
