### ISSUE TITLE
Rename things in CarrierService / CarrierShipment, to have this consistent. 

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#3509]
Also adapt the fields in the xml file as well. 

This is a first step on the way to maybe introduce something lika a "CarrierJob" on MATSim-level, which can have 1 or 2 locations. If it is a 1-location job, jsprit uses "Services", if it has 2 locations, it uses "Shipments".

**Comment by kt86** [comment]
This will lead in the end to a new carrierDefinition XSD...

**Comment by rewertvsp** [comment]
- einheitliche Benennung zwischen Service und Shipment (z.B. TimeWindows, Demand/Size...)
