### ISSUE TITLE
clarify NoiseAnalysis

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-libs#3519]
The class `NoiseAnalysis`, which is used from the noise analysis branch of the application contrib, probably does not exclude bicycles.  This needs to be understood and clarified, and then the most typical use cases either need to be included by default, or made configurable.

It seems that all modes that are not explicitly excluded are classified as "pkw".  I am wondering a bit if we should maybe proceed as in emissions, where the emissions vehicle type needs to be in the vehicle attributes.  

This should then possibly be set in the scenario runscript (so that allVehicles already contains the correct information).  (The same would then hold for particulate emissions.)

Related:
#3520 

To check:
#3328 #3315 #3495

**Comment by tschlenther** [comment]
1. the ID stuff should be replaced

2. start ticket which says thaat we should have separate network modes for heavy vehicles (buses AND trucks separetely; i.e. < 3,5t, <7,5t, <12t, ....). 
* think about how this works for countries outside Germany.... 
* think about the travel time observer 

3. start ticket which replaces the Id-based NoiseVehicle lookup by introducing a NoiseVehicleType (similar to HbefaVehicleType)
