### ISSUE TITLE
Several Test failures on macOS (and Windows) in full-integration pipeline

### ISSUE THREAD

**Issue by jfbischoff** [matsim-org/matsim-libs#3535]
Hello,

I've noticed that the full-integration pipeline keeps on failing, not only because of some Windows tests, but also many MacOs related tests:
https://github.com/matsim-org/matsim-libs/actions/runs/11623035269
Some examples
- SignalSystemsIT
- RunEvExampleTest
All of these tests run on Ubuntu.
I'm currently looking on the Windows tests failing and will try to fix them in the next couple of days, but overall this raises some questions:
- Do we care about these test failures? Or are we happy as long as they run on Linux?
--> If we don't care, we should disable the pipeline, if we care, we should fix them.

Since I don't have a Mac, I can't really help with fixing - but will try to keep an eye on the Windows pipeline.

Bests,
Joschka

**Comment by jfbischoff** [comment]
The build is now running again on Windows, but continues to fail on macOS:
https://github.com/matsim-org/matsim-libs/actions/runs/11695784477

Is anyone with a mac willing to look into this?
@Janekdererste et al?
Probably just small things. 
If not, I think it's better to disable the macos-build of all contribs rather than having it continously fail.

**Comment by Janekdererste** [comment]
Sorry, I didn't have time yet. Do we still need to look into it for macOS?

**Comment by jfbischoff** [comment]
@Janekdererste : Unfortunately, yes. 
Right now, there are some failing tests on windows again, but I'll look into them.

**Comment by jfbischoff** [comment]
For the time being, tests on mac-os latests have been disabled in the pipeline.
https://github.com/matsim-org/matsim-libs/pull/3603
