### ISSUE TITLE
Change Java version to 11

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-libs#846]
Chage Matsim's java version to 11.

This includes:

- Change compilation target
- Update some maven plugins which are not compatible with java 11
- Update jenkins configuration, and install a suitable jdk

**Comment by Janekdererste** [comment]
An extensive discussion exists in our old issue tracker
https://matsim.atlassian.net/browse/MATSIM-882?atlOrigin=eyJpIjoiMjM5NmUwMGI0YjMzNGNlNGEyZTc0YTYwNjhkY2YzMGMiLCJwIjoiaiJ9

**Comment by mrieser** [comment]
I just pushed some changes to the branch `java-11`. Calling `mvn clean install javadoc:javadoc -DskipTests=true` (similar to what Jenkins calls) now works locally with openjdk 11.0.5.

**Comment by mrieser** [comment]
I would suggest disabling PMD and Findbugs for Java 11. At least Findbugs hasn't seen an update for years and might not even support all Java 11 byte-code features (there is actually a follow-up project, [SpotBugs](https://spotbugs.github.io) which we could enable later if we want).
Anybody against that?

**Comment by michalmac** [comment]
Findbugs seems to be dead. So I vote for disabling it. I think it also generates lots of false positives.

PMD - never really used :-)

SpotBugs works fine and is maintained, so we could enable tit at some point. Same for Google's  Error Prone: https://errorprone.info/

**Comment by mrieser** [comment]
Cool, I didn't know errorprone.
