### ISSUE TITLE
drt reservations (= reserve drt for extended period of time)

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-libs#848]

**Comment by tschlenther** [comment]
WIP:

we (@michalmac and @tschlenther) agreed on the following things:
- 

1. a custom `VehicleDataEntryFactory` prevents the standard drt optimizer from 'using' blocked vehicles
2. a blocking optimizer is wrapped around the standard drt optimizer and hands over conventional passenger requests
3. use a separate channels for blocking requests and conventional passenger requests. Very similar to the `OneTruckExample`
4. blocking requests contain DVRPTasks. That means, there is no (virtual) passenger on board during the blocked time period- For instance, freight agents would not be explicitly modeled and could not replan (replanning for freight is usually done on a higher = carriers level, anyways). This comes with the advantage of more flexibility, e.g. interrupting tours. This requires proper modeling of (freight) tasks and conversion from tours.
5. _Just for notice: In some other approach, i had hacked the drt infrastructure in a way that the freight agent is a regular drt passenger and a blocking request is also of type `PassengerRequest`. The handling of blocked vehicles would actually take place in the `UnplannedRequestInserter` which would only allow one single vehicle for BlockingRequests. This is rather deep hack into dvrp infrastructure that does not need a lot of coding but does not create any flexibility, e.g. for interrupting tours._
6. - The availibility of drt vehicles for blocking should be time-dependent. I created an interface `DrtBlockingManager` and an implementation that allows to define a maximum number of blocked vehicles per time slot.

@michalmac please feel free to add and correct if have overlooked something :)

I have implemented most of the infrastructure and will work on the corresponding module and some run example. Right now, the code is in another (project) repo, i will move it to the commercialTrafficApplications contrib when it is done.
