### ISSUE TITLE
move parking proxy into parking contrib

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-libs#853]

**Comment by kainagel** [comment]
See #840 for some discussion of `new XyzModule( scenario )`.  Results is that for the time being we can leave it like that, but keep in mind that one cannot use it together with `Controler` that is instantiated from config only.  Since that is not recommended anyways, it does not seem like a major issue.

**Comment by Royal2Flush** [comment]
https://github.com/matsim-org/matsim-libs/pull/872
