### ISSUE TITLE
have access mode(s) definable for network routing

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-libs#900]
In pt routing (raptor), we already have that: one can define a set of possible access modes, such as `walk` and `drt`.  It seems that we should have the same for network routing.  To recall, "network routing" is a generalized approach which is used for all individual modes, such as `car` and `bike`, but also `walk` when done on the network.

Use cases for definable access modes are:
* sbb said that they want to be able to differentiate, say, between (walk-)access-to-rail and (walk-)access-to-car.
* @dziemke had a case where he wanted to parameterize car access to the primary road network without explicitly having to simulate residential streets.

In general, it seems that we would use the same approach as we are now using in the sbb raptor, which is that the access mode routers are taken from the `TripRouter`, i.e. they need to be defined explicitly, either as teleportation routers, or as something else.

There are two related questions:
1. Do we want only one access mode per network mode, or possibly multiple access modes?
2. Do we implement this in the config as comma-separated list, or using `ParameterSet`?

Comma-separated list would be easier to implement.  However, it would give us only one access mode per network routing mode.

With `ParameterSet`, the question is what it would look like.  Possibly something like this, to avoid a second hierarchy:
```
<parameterSet name="accessMode">
   <name="networkRoutingMode" value="car" />
   <name="accessEgressMode" value="walk" />
</parameterSet>
<parameterSet name="accessMode">
   <name="networkRoutingMode" value="car" />
   <name="accessEgressMode" value="bike" /> // second access mode for car
</parameterSet>
<parameterSet name="accessMode">
   <name="networkRoutingMode" value="bike" />
   <name="accessEgressMode" value="walk" /> // access mode for bicycle
</parameterSet>
```

Or rather:
```
<parameterSet type="networkRoutingConfig">
    <param name="networkRoutingMode" value="car">
    <param name="accessEgressModes" value="car_access_walk,eScooter" />
</parameterSet>
<parameterSet type="networkRoutingConfig">
    <param name="networkRoutingMode" value="bicycle">
    <param name="accessEgressModes" value="bicycle_access_walk" />
</parameterSet>
```
???

Any opinions?

**Comment by tschlenther** [comment]
i think this is addressed by #1041 which is not proposing anything on the config file level yet
