### ISSUE TITLE
Bug in the InsertionGenerator of the DRT extension

### ISSUE THREAD

**Issue by vbuchhold** [matsim-org/matsim-libs#912]
I think there might be bug in `InsertionGenerator::generateDropoffInsertions`. Consider a situation where we have an outgoing occupancy of 0 at stop 0 and an outgoing occupancy of "capacity" at stop 1. It is possible to transport a new passenger from stop 0 to stop 1, but the current implementation does not generate this candidate insertion.

**Comment by michalmac** [comment]
@vbuchhold Thanks for reporting this bug. I added unit tests in this PR: #976, however I could not reproduce the bug (based on the issue description).

**Comment by vbuchhold** [comment]
@michalmac Thanks for your answer! As far as I see it, your unit tests do not cover the specific family of special cases I was referring to. None of your tests considers a situation where the request's pickup or dropoff location coincides with the location of an already existing stop. When I wrote "It is possible to transport a new passenger from stop 0 to stop 1..." I meant that stop 0 coincides with the new pickup and stop 1 coincides with the new dropoff. Sorry if this was not clear.

Maybe you can add something similar to the following unit test that implements the situation I originally had in mind. I would expect that it fails. I am sorry that I currently cannot run it myself.

```
	@Test
	public void generateInsertions_coincidingPickupAndDropoff() {
		LinkTimePair start = new LinkTimePair(fakeLink("start"), 0);
		int startOccupancy = CAPACITY; //full
		VehicleData.Stop stop0 = stop(fakeLink("from"), 0);// dropoff 4 pax
		VehicleData.Stop stop1 = stop(fakeLink("to"), CAPACITY);// pickup 4 pax
		VehicleData.Stop stop2 = stop(fakeLink("stop2"), 0);// dropoff 4 pax
		VehicleData.Entry entry = entry(start, startOccupancy, stop0, stop1, stop2);
		assertThatInsertions(drtRequest, entry).containsExactly(
				//no pickup after start
				//pickup after stop 0
				insertion(1, 1),
				//pickup after stop 1
				//pickup after stop 2
				insertion(3, 3));
	}
```

**Comment by michalmac** [comment]
@vbuchhold Thanks a lot! Found it. There are 2 conditions that must be met to trigger that bug:
- the dropoff exactly at an existing stop
- the vehicle departs fully occupied from that stop (this was not covered in tests)
