### ISSUE TITLE
DRT (DVRP) passenger's state is not set to abort

### ISSUE THREAD

**Issue by tschlenther** [matsim-org/matsim-libs#923]
In DRT, a `PassengerReqeuestRejectedEvent `is thrown if no insertion could be found for a request (see DefaultUnplannedRequestInserter for an example).

The class `PassengerRequestEventToPassengerEngineForwarder` notifies the corresponding `PassengerEngine` about that event. Currently, the `PassengerEngine `has two ways to react, depending on whether the request was a prebooking request or not:

1.) if the request was a prebooking request, notify the `PreplanningEngine`
2.) else throw a PersonStuckEvent

Now here comes the problem (as i see it):

The state of the actual MobsimAgent never is set to ABORT.
In the QSim, the agent only is removed of the agent's state is set to ABORT.

That means: if (for whatever reason) no insertion can be found for a passenger, the qsim runs forever (if no end time was defined).

I know that in general, we want to avoid rejections in the first place. However, this seems to be a bug for me..  (and GL) .. !?

A possible solution would be that the PassengerEngine sets the MobsimAgent's state to ABORT. I will present this in a PR shortly.

**Comment by kainagel** [comment]
I think this makes sense.  can't say if it was fixed in the meantime.

**Comment by tschlenther** [comment]
Actually, in DrtConfigGroup, there was a warning message about this. So it seems like this was known and maybe even designed in that way on purpose.. ?!
Still, in my opinion, setting those agents to abort instead of having the qsim run forever is the better solution.

**Comment by kainagel** [comment]
sure it is better to fix it.  actually saw your commit shortly afterwards; thank you.  (Or is it not yet merged?)

**Comment by tschlenther** [comment]
It is not yet merged. Since you approved it, i put the automerge label on it.

**Comment by michalmac** [comment]
Makes sense for me, too! 👍
