### ISSUE TITLE
Listener to be implemented for vehicle start/stop?

### ISSUE THREAD

**Issue by amrlafi** [matsim-org/matsim-libs#926]
Hey,
I'm unclear which Listener handles vehicle start and stop. I would like to listen to each vehicle start and stop events. Is it possible with MATSim?

**Comment by mrieser** [comment]
There are no such events. The closest ones are probably the person-departure and person-arrival events with the mode "car", or alternatively the vehicle-enters-traffic and vehicle-leaves-traffic events. All of these only cover private cars, but not public transport.

**Comment by amrlafi** [comment]
Given that the vehicle have a unique ID, would it be possible to achieve this using custom events?

**Comment by Janekdererste** [comment]
I'm closing this issue since nothing has changed for a month. It seems to me that this is more of a question for the Q&A Board, wich can be found here: https://github.com/matsim-org/matsim-code-examples/issues

Please ask your questions about matsim there.
