### ISSUE TITLE
EV custom run

### ISSUE THREAD

**Issue by NofTheGreek** [matsim-org/matsim-libs#975]
Hi, I want to make a custom RunEvExample because I want to get every vehicle's (agent's) consumption , for example every 10 seconds.  More particular, I want to get the battery's info , vehicle's made kilometers and charger's info. Does anyone know where I can get these values? 
Thank you in advance

**Comment by Janekdererste** [comment]
I think this is a question for our q&a board. Which you can find [here](https://github.com/matsim-org/matsim-code-examples/issues)
